/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fit.iuh.qlbhtt;


import fit.iuh.entity.NhanVien;

import java.awt.Color;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 * @author DMX
 */
public  class HomePage extends javax.swing.JFrame {

    private  final NhanVien nhanVien = Login.nhanVien;
    private  final boolean ngonNgu = Login.ngonNgu;

    /**
     * Creates new form HomePage
     */
    public  HomePage() throws SQLException {
        initComponents();
        setTitle("Quản Lý Bán Quần Áo Thời Trang");
        setExtendedState(JFrame.MAXIMIZED_BOTH);


        if (!ngonNgu) {
            chuyenDoiNgonNgu();
            if (nhanVien.getChuVu().equals("Nhân Viên")) {
                String chucVu = nhanVien.getChuVu().replace("Nhân Viên", "Staff");
                mnu_TenNVDangNhap.setText(chucVu + ": " + nhanVien.getHoTen());
            } else {
                String chucVu = nhanVien.getChuVu().replace("Quản lý", "Manager");
                mnu_TenNVDangNhap.setText(chucVu + ": " + nhanVien.getHoTen());
            }
        } else {
            mnu_TenNVDangNhap.setText(nhanVien.getChuVu() + ": " + nhanVien.getHoTen());
        }
        setRole();
    }

    public synchronized void chuyenDoiNgonNgu() {
        mnu_SanPham.setText("Clothes");
        mni_SP_QuanLy.setText("Management");
        mni_SP_TimKiem.setText("Search");
        mni_SP_ChatLieu.setText("Fabric");
        mni_SP_MauSac.setText("Color");
        mni_SP_KichThuoc.setText("Size");
        mni_SP_DanhMuc.setText("Category");

        mnu_PhuKien.setText("Accessory");
        mni_PK_QuanLy.setText("Management");
        mni_PK_TimKiem.setText("Search");

        mnu_NhanVien.setText("Staff");
        mni_NV_DatHang.setText("Order");
        mni_NV_LapHoaDon.setText("Make an invoice");
        mni_NV_HuyDonDat.setText("Cancel Order");
        mni_NV_ThongKeDoanhThu.setText("Revenue Statistics");
        mni_NV_ThongKeSanPham.setText("Product Statistics");
        mni_NV_ThongKeThongTinKH.setText("Customer Statistics");
        mni_NV_XemDSHoaDon.setText("View invoice list");
        mni_NV_QuanLy.setText("Management");
        mni_NV_TimKiem.setText("Search");

        mnu_KhachHang.setText("Customer");
        mni_KH_QuanLy.setText("Management");
        mni_KH_TimKiem.setText("Search");

        mnu_TaiKhoan.setText("Account");
        mni_TK_QuanLy.setText("Management");
        mnu_NhaCungCap.setText("Supplier");
        mni_NCC_QuanLy.setText("Management");
        mni_NCC_TimKiem.setText("Search");

        mnu_DangXuat.setText("Log out");

    }

    /**
     * Cài đặt role khi nhân viên đăng nhập
     */
    public synchronized void setRole() {
        if (nhanVien.getChuVu().equalsIgnoreCase("Nhân Viên")) {
            //mni_SP_ChatLieu.setVisible(false);
            //mni_SP_MauSac.setVisible(false);
            // mni_SP_KichThuoc.setVisible(false);
            //mni_SP_DanhMuc.setVisible(false);
            mni_NV_QuanLy.setVisible(false);
            //mni_NV_TimKiem.setVisible(false);
            mnu_TaiKhoan.setVisible(false);
            //mnu_NhaCungCap.setVisible(false);

            anThanhNgang(false);
        }
    }

    /**
     * Ẩn thanh ngang
     */
    public synchronized void anThanhNgang(boolean kiemTra) {
        //spr_SP_ThanhNgang1.setVisible(kiemTra);
        //spr_SP_ThanhNgang2.setVisible(kiemTra);
        //spr_SP_ThanhNgang3.setVisible(kiemTra);
        //spr_SP_ThanhNgang4.setVisible(kiemTra);

        spr_NV_ThanhNgang6.setVisible(kiemTra);
        //spr_NV_ThanhNgang7.setVisible(kiemTra);

    }

    //tạo hàm mở tab quản lý nhân viên
    public synchronized static void activeQLNVForm() {
        ManHinh_NV_QuanLy pnl_NV_QuanLy = null;
        try {
            pnl_NV_QuanLy = new ManHinh_NV_QuanLy();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_QuanLy);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private synchronized void initComponents() {

        pnl_GiaoDienChucNang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mnu_ManHinhChinh = new javax.swing.JMenuBar();
        mnu_SanPham = new javax.swing.JMenu();
        mni_SP_QuanLy = new javax.swing.JMenuItem();
        spr_SP_ThanhNgang = new javax.swing.JPopupMenu.Separator();
        mni_SP_TimKiem = new javax.swing.JMenuItem();
        spr_SP_ThanhNgang1 = new javax.swing.JPopupMenu.Separator();
        mni_SP_ChatLieu = new javax.swing.JMenuItem();
        spr_SP_ThanhNgang2 = new javax.swing.JPopupMenu.Separator();
        mni_SP_MauSac = new javax.swing.JMenuItem();
        spr_SP_ThanhNgang3 = new javax.swing.JPopupMenu.Separator();
        mni_SP_KichThuoc = new javax.swing.JMenuItem();
        spr_SP_ThanhNgang4 = new javax.swing.JPopupMenu.Separator();
        mni_SP_DanhMuc = new javax.swing.JMenuItem();
        mnu_PhuKien = new javax.swing.JMenu();
        mni_PK_QuanLy = new javax.swing.JMenuItem();
        spr_PK_ThanhNgang = new javax.swing.JPopupMenu.Separator();
        mni_PK_TimKiem = new javax.swing.JMenuItem();
        mnu_NhanVien = new javax.swing.JMenu();
        mni_NV_DatHang = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang1 = new javax.swing.JPopupMenu.Separator();
        mni_NV_LapHoaDon = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang2 = new javax.swing.JPopupMenu.Separator();
        mni_NV_HuyDonDat = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang8 = new javax.swing.JPopupMenu.Separator();
        mni_NV_ThongKeDoanhThu = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang3 = new javax.swing.JPopupMenu.Separator();
        mni_NV_ThongKeSanPham = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang4 = new javax.swing.JPopupMenu.Separator();
        mni_NV_ThongKeThongTinKH = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang5 = new javax.swing.JPopupMenu.Separator();
        mni_NV_XemDSHoaDon = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang6 = new javax.swing.JPopupMenu.Separator();
        mni_NV_QuanLy = new javax.swing.JMenuItem();
        spr_NV_ThanhNgang7 = new javax.swing.JPopupMenu.Separator();
        mni_NV_TimKiem = new javax.swing.JMenuItem();
        mnu_KhachHang = new javax.swing.JMenu();
        mni_KH_QuanLy = new javax.swing.JMenuItem();
        spr_ThanhNgang9 = new javax.swing.JPopupMenu.Separator();
        mni_KH_TimKiem = new javax.swing.JMenuItem();
        mnu_TaiKhoan = new javax.swing.JMenu();
        mni_TK_QuanLy = new javax.swing.JMenuItem();
        mnu_NhaCungCap = new javax.swing.JMenu();
        mni_NCC_QuanLy = new javax.swing.JMenuItem();
        spr_ThanhNgang10 = new javax.swing.JPopupMenu.Separator();
        mni_NCC_TimKiem = new javax.swing.JMenuItem();
        mnu_DangXuat = new javax.swing.JMenu();
        mnu_TenNVDangNhap = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_GiaoDienChucNang.setPreferredSize(new java.awt.Dimension(746, 423));
        pnl_GiaoDienChucNang.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/Ảnh nền chính-sua1.png")); // NOI18N
        pnl_GiaoDienChucNang.add(jLabel1, java.awt.BorderLayout.LINE_START);

        mnu_ManHinhChinh.setBackground(new java.awt.Color(206, 230, 243));
        mnu_ManHinhChinh.setMinimumSize(new java.awt.Dimension(383, 50));
        mnu_ManHinhChinh.setPreferredSize(new java.awt.Dimension(383, 50));

        mnu_SanPham.setBackground(new java.awt.Color(242, 242, 242));
        mnu_SanPham.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-shirt-35.png")); // NOI18N
        mnu_SanPham.setText("Quần Áo");
        mnu_SanPham.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mnu_SanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnu_SanPham.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnu_SanPham.setPreferredSize(new java.awt.Dimension(250, 30));

        mni_SP_QuanLy.setBackground(new java.awt.Color(224, 224, 222));
        mni_SP_QuanLy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_SP_QuanLy.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/document-paper (1).png")); // NOI18N

        mni_SP_QuanLy.setText("Quản Lý");
        mni_SP_QuanLy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mni_SP_QuanLy.setPreferredSize(new java.awt.Dimension(160, 35));
        mni_SP_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_SP_QuanLyActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_SP_QuanLy);
        mnu_SanPham.add(spr_SP_ThanhNgang);

        mni_SP_TimKiem.setBackground(new java.awt.Color(224, 224, 222));
        mni_SP_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_SP_TimKiem.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/research-doi.png")); // NOI18N
        mni_SP_TimKiem.setText("Tìm Kiếm");
        mni_SP_TimKiem.setPreferredSize(new java.awt.Dimension(117, 35));
        mni_SP_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_SP_TimKiemActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_SP_TimKiem);
        mnu_SanPham.add(spr_SP_ThanhNgang1);

        mni_SP_ChatLieu.setBackground(new java.awt.Color(224, 224, 222));
        mni_SP_ChatLieu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_SP_ChatLieu.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-fabric-30.png")); // NOI18N
        mni_SP_ChatLieu.setText("Chất Liệu");
        mni_SP_ChatLieu.setPreferredSize(new java.awt.Dimension(117, 35));
        mni_SP_ChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_SP_ChatLieuActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_SP_ChatLieu);
        mnu_SanPham.add(spr_SP_ThanhNgang2);

        mni_SP_MauSac.setBackground(new java.awt.Color(224, 224, 222));
        mni_SP_MauSac.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_SP_MauSac.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-color-30.png")); // NOI18N
//        java.net.URL url5 = getClass().getResource("icons8-color-30.pn");
//        if (url5 != null) {
//            // Resource is loaded successfully, set the icon
//            mni_SP_MauSac.setIcon(new javax.swing.ImageIcon(url5));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: icons8-color-30.png");
//        }
        mni_SP_MauSac.setText("Màu Sắc");
        mni_SP_MauSac.setPreferredSize(new java.awt.Dimension(112, 35));
        mni_SP_MauSac.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_SP_MauSacActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_SP_MauSac);
        mnu_SanPham.add(spr_SP_ThanhNgang3);

        mni_SP_KichThuoc.setBackground(new java.awt.Color(224, 224, 222));
        mni_SP_KichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_SP_KichThuoc.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-size-30.png")); // NOI18N
//        java.net.URL url6 = getClass().getResource("icons8-size-30.png");
//        if (url6 != null) {
//            // Resource is loaded successfully, set the icon
//            mni_SP_KichThuoc.setIcon(new javax.swing.ImageIcon(url6));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: icons8-size-30.png");
//        }
        mni_SP_KichThuoc.setText("Kích Thước");
        mni_SP_KichThuoc.setPreferredSize(new java.awt.Dimension(126, 35));
        mni_SP_KichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_SP_KichThuocActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_SP_KichThuoc);
        mnu_SanPham.add(spr_SP_ThanhNgang4);

        mni_SP_DanhMuc.setBackground(new java.awt.Color(224, 224, 222));
        mni_SP_DanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_SP_DanhMuc.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-category-30.png")); // NOI18N
//        java.net.URL url7 = getClass().getResource("icons8-category-30.png");
//        if (url7 != null) {
//            // Resource is loaded successfully, set the icon
//            mni_SP_DanhMuc.setIcon(new javax.swing.ImageIcon(url7));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: icons8-category-30.png");
//        }
        mni_SP_DanhMuc.setText("Danh Mục");
        mni_SP_DanhMuc.setPreferredSize(new java.awt.Dimension(122, 35));
        mni_SP_DanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_SP_DanhMucActionPerformed(evt);
            }
        });
        mnu_SanPham.add(mni_SP_DanhMuc);

        mnu_ManHinhChinh.add(mnu_SanPham);

        mnu_PhuKien.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-trainers-35.png")); // NOI18N
//        java.net.URL url8 = getClass().getResource("icons8-trainers-35.png");
//        if (url8 != null) {
//            // Resource is loaded successfully, set the icon
//            mnu_PhuKien.setIcon(new javax.swing.ImageIcon(url8));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: icons8-trainers-35.png");
//        }
        mnu_PhuKien.setText("Phụ Kiện");
        mnu_PhuKien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnu_PhuKien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnu_PhuKien.setMinimumSize(new java.awt.Dimension(250, 22));
        mnu_PhuKien.setPreferredSize(new java.awt.Dimension(250, 30));

        mni_PK_QuanLy.setBackground(new java.awt.Color(224, 224, 222));
        mni_PK_QuanLy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_PK_QuanLy.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/document-paper (1).png")); // NOI18N
//        java.net.URL url9 = getClass().getResource("document-paper (1).png");
//        if (url9 != null) {
//            // Resource is loaded successfully, set the icon
//            mni_PK_QuanLy.setIcon(new javax.swing.ImageIcon(url9));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: document-paper (1).png");
//        }
        mni_PK_QuanLy.setText("Quản Lý");
        mni_PK_QuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mni_PK_QuanLy.setPreferredSize(new java.awt.Dimension(160, 36));
        mni_PK_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_PK_QuanLyActionPerformed(evt);
            }
        });
        mnu_PhuKien.add(mni_PK_QuanLy);
        mnu_PhuKien.add(spr_PK_ThanhNgang);

        mni_PK_TimKiem.setBackground(new java.awt.Color(224, 224, 222));
        mni_PK_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_PK_TimKiem.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/research-doi.png")); // NOI18N
//        java.net.URL url10 = getClass().getResource("research-doi.png");
//        if (url10 != null) {
//            // Resource is loaded successfully, set the icon
//            mni_PK_TimKiem.setIcon(new javax.swing.ImageIcon(url10));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: research-doi.png");
//        }
        mni_PK_TimKiem.setText("Tìm Kiếm");
        mni_PK_TimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mni_PK_TimKiem.setPreferredSize(new java.awt.Dimension(102, 36));
        mni_PK_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_PK_TimKiemActionPerformed(evt);
            }
        });
        mnu_PhuKien.add(mni_PK_TimKiem);

        mnu_ManHinhChinh.add(mnu_PhuKien);

        mnu_NhanVien.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-crowd-skin-type-1-35.png")); // NOI18N
//        java.net.URL url11 = getClass().getResource("icons8-crowd-skin-type-1-35.png");
//        if (url11 != null) {
//            // Resource is loaded successfully, set the icon
//            mnu_NhanVien.setIcon(new javax.swing.ImageIcon(url11));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: icons8-crowd-skin-type-1-35.png");
//        }
        mnu_NhanVien.setText("Nhân Viên");
        mnu_NhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnu_NhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnu_NhanVien.setMinimumSize(new java.awt.Dimension(250, 22));
        mnu_NhanVien.setPreferredSize(new java.awt.Dimension(250, 30));

        mni_NV_DatHang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        mni_NV_DatHang.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_DatHang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_DatHang.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/shop.png")); // NOI18N
//        java.net.URL url12 = getClass().getResource("shop.png");
//        if (url12 != null) {
//            // Resource is loaded successfully, set the icon
//            mni_NV_DatHang.setIcon(new javax.swing.ImageIcon(url12));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: shop.png");
//        }
        mni_NV_DatHang.setText("Đặt Hàng");
        mni_NV_DatHang.setMinimumSize(new java.awt.Dimension(220, 35));
        mni_NV_DatHang.setPreferredSize(new java.awt.Dimension(220, 35));
        mni_NV_DatHang.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_DatHangActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_DatHang);
        mnu_NhanVien.add(spr_NV_ThanhNgang1);

        mni_NV_LapHoaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        mni_NV_LapHoaDon.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_LapHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_LapHoaDon.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/copywriting-fax.png")); // NOI18N
//        java.net.URL url13 = getClass().getResource("copywriting-fax.png");
//        if (url13 != null) {
//            // Resource is loaded successfully, set the icon
//            mni_NV_LapHoaDon.setIcon(new javax.swing.ImageIcon(url13));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: copywriting-fax.png");
//        }
        mni_NV_LapHoaDon.setText("Lập Hóa Đơn");
        mni_NV_LapHoaDon.setPreferredSize(new java.awt.Dimension(121, 35));
        mni_NV_LapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_LapHoaDonActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_LapHoaDon);
        mnu_NhanVien.add(spr_NV_ThanhNgang2);

        mni_NV_HuyDonDat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        mni_NV_HuyDonDat.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_HuyDonDat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_HuyDonDat.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-delete-document-30.png")); // NOI18N

        mni_NV_HuyDonDat.setText("Hủy đơn đặt");
        mni_NV_HuyDonDat.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_HuyDonDatActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_HuyDonDat);
        mnu_NhanVien.add(spr_NV_ThanhNgang8);

        mni_NV_ThongKeDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        mni_NV_ThongKeDoanhThu.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_ThongKeDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_ThongKeDoanhThu.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/monitoring-evaluation.png")); // NOI18N
        mni_NV_ThongKeDoanhThu.setText("Thống Kê Doanh Thu");
        mni_NV_ThongKeDoanhThu.setPreferredSize(new java.awt.Dimension(163, 35));
        mni_NV_ThongKeDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_ThongKeDoanhThuActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_ThongKeDoanhThu);
        mnu_NhanVien.add(spr_NV_ThanhNgang3);

        mni_NV_ThongKeSanPham.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mni_NV_ThongKeSanPham.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_ThongKeSanPham.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_ThongKeSanPham.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/board-analysis.png")); // NOI18N

        mni_NV_ThongKeSanPham.setText("Thống Kê Sản Phẩm");
        mni_NV_ThongKeSanPham.setPreferredSize(new java.awt.Dimension(158, 35));
        mni_NV_ThongKeSanPham.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_ThongKeSanPhamActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_ThongKeSanPham);
        mnu_NhanVien.add(spr_NV_ThanhNgang4);

        mni_NV_ThongKeThongTinKH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mni_NV_ThongKeThongTinKH.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_ThongKeThongTinKH.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_ThongKeThongTinKH.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/document-business.png")); // NOI18N
        mni_NV_ThongKeThongTinKH.setText("Thống Kê Thông Tin Khách Hàng");
        mni_NV_ThongKeThongTinKH.setPreferredSize(new java.awt.Dimension(245, 35));
        mni_NV_ThongKeThongTinKH.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_ThongKeThongTinKHActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_ThongKeThongTinKH);
        mnu_NhanVien.add(spr_NV_ThanhNgang5);

        mni_NV_XemDSHoaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        mni_NV_XemDSHoaDon.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_XemDSHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_XemDSHoaDon.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/shoping.png")); // NOI18N
        mni_NV_XemDSHoaDon.setText("Xem Danh Sách Hóa Đơn");
        mni_NV_XemDSHoaDon.setPreferredSize(new java.awt.Dimension(185, 35));
        mni_NV_XemDSHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_XemDSHoaDonActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_XemDSHoaDon);
        mnu_NhanVien.add(spr_NV_ThanhNgang6);

        mni_NV_QuanLy.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_QuanLy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_QuanLy.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/document-paper (1).png")); // NOI18N
        mni_NV_QuanLy.setText("Quản Lý");
        mni_NV_QuanLy.setPreferredSize(new java.awt.Dimension(96, 35));
        mni_NV_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_QuanLyActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_QuanLy);
        mnu_NhanVien.add(spr_NV_ThanhNgang7);

        mni_NV_TimKiem.setBackground(new java.awt.Color(224, 224, 222));
        mni_NV_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NV_TimKiem.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/research-doi.png")); // NOI18N
        mni_NV_TimKiem.setText("Tìm Kiếm");
        mni_NV_TimKiem.setPreferredSize(new java.awt.Dimension(102, 35));
        mni_NV_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NV_TimKiemActionPerformed(evt);
            }
        });
        mnu_NhanVien.add(mni_NV_TimKiem);

        mnu_ManHinhChinh.add(mnu_NhanVien);

        mnu_KhachHang.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-person-35.png")); // NOI18N
        mnu_KhachHang.setText("Khách Hàng");
        mnu_KhachHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnu_KhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnu_KhachHang.setPreferredSize(new java.awt.Dimension(250, 30));

        mni_KH_QuanLy.setBackground(new java.awt.Color(224, 224, 222));
        mni_KH_QuanLy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_KH_QuanLy.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/document-paper (1).png")); // NOI18N

        mni_KH_QuanLy.setText("Quản Lý");
        mni_KH_QuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mni_KH_QuanLy.setPreferredSize(new java.awt.Dimension(96, 35));
        mni_KH_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_KH_QuanLyActionPerformed(evt);
            }
        });
        mnu_KhachHang.add(mni_KH_QuanLy);
        mnu_KhachHang.add(spr_ThanhNgang9);

        mni_KH_TimKiem.setBackground(new java.awt.Color(224, 224, 222));
        mni_KH_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_KH_TimKiem.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/research-doi.png")); // NOI18N
        mni_KH_TimKiem.setText("Tìm Kiếm");
        mni_KH_TimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mni_KH_TimKiem.setPreferredSize(new java.awt.Dimension(160, 35));
        mni_KH_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_KH_TimKiemActionPerformed(evt);
            }
        });
        mnu_KhachHang.add(mni_KH_TimKiem);

        mnu_ManHinhChinh.add(mnu_KhachHang);

        mnu_TaiKhoan.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-account-35.png")); // NOI18N
        mnu_TaiKhoan.setText("Tài Khoản");
        mnu_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnu_TaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnu_TaiKhoan.setPreferredSize(new java.awt.Dimension(250, 30));

        mni_TK_QuanLy.setBackground(new java.awt.Color(224, 224, 222));
        mni_TK_QuanLy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_TK_QuanLy.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/card (1).png")); // NOI18N
        mni_TK_QuanLy.setText("Quản Lý");
        mni_TK_QuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mni_TK_QuanLy.setPreferredSize(new java.awt.Dimension(160, 35));
        mni_TK_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_TK_QuanLyActionPerformed(evt);
            }
        });
        mnu_TaiKhoan.add(mni_TK_QuanLy);

        mnu_ManHinhChinh.add(mnu_TaiKhoan);

        mnu_NhaCungCap.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-supplier-35.png")); // NOI18N
        mnu_NhaCungCap.setText("Nhà Cung Cấp");
        mnu_NhaCungCap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnu_NhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnu_NhaCungCap.setPreferredSize(new java.awt.Dimension(250, 30));

        mni_NCC_QuanLy.setBackground(new java.awt.Color(224, 224, 222));
        mni_NCC_QuanLy.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NCC_QuanLy.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/document-paper (1).png")); // NOI18N
        mni_NCC_QuanLy.setText("Quản Lý");
        mni_NCC_QuanLy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mni_NCC_QuanLy.setPreferredSize(new java.awt.Dimension(160, 35));
        mni_NCC_QuanLy.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NCC_QuanLyActionPerformed(evt);
            }
        });
        mnu_NhaCungCap.add(mni_NCC_QuanLy);
        mnu_NhaCungCap.add(spr_ThanhNgang10);

        mni_NCC_TimKiem.setBackground(new java.awt.Color(224, 224, 222));
        mni_NCC_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        mni_NCC_TimKiem.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/research-doi.png")); // NOI18N
        mni_NCC_TimKiem.setText("Tìm Kiếm");
        mni_NCC_TimKiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mni_NCC_TimKiem.setPreferredSize(new java.awt.Dimension(160, 35));
        mni_NCC_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mni_NCC_TimKiemActionPerformed(evt);
            }
        });
        mnu_NhaCungCap.add(mni_NCC_TimKiem);

        mnu_ManHinhChinh.add(mnu_NhaCungCap);

        mnu_DangXuat.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-exit-35.png")); // NOI18N
        mnu_DangXuat.setText("Đăng xuất");
        mnu_DangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mnu_DangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mnu_DangXuat.setMinimumSize(new java.awt.Dimension(120, 22));
        mnu_DangXuat.setPreferredSize(new java.awt.Dimension(200, 30));
        mnu_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseClicked(java.awt.event.MouseEvent evt) {
                mnu_DangXuatMouseClicked(evt);
            }
        });
        mnu_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_DangXuatActionPerformed(evt);
            }
        });
        mnu_ManHinhChinh.add(mnu_DangXuat);

        mnu_TenNVDangNhap.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-user-30.png")); // NOI18N
//        java.net.URL url30 = getClass().getResource("icons8-user-30.png");
//        if (url30 != null) {
//            // Resource is loaded successfully, set the icon
//            mnu_TenNVDangNhap.setIcon(new javax.swing.ImageIcon(url30));
//        } else {
//            // Resource not found, print an error message
//            System.err.println("Resource not found: icons8-user-30.png");
//        }
        mnu_TenNVDangNhap.setText("Nhân Viên: ");
        mnu_TenNVDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnu_ManHinhChinh.add(mnu_TenNVDangNhap);

        setJMenuBar(mnu_ManHinhChinh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_GiaoDienChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 1992, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_GiaoDienChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private synchronized void mni_SP_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_SP_QuanLyActionPerformed
        // TODO add your handling code here:
        ManHinh_QA_QuanLy pnl_QuanLySP = null;
        try {
            pnl_QuanLySP = new ManHinh_QA_QuanLy();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_QuanLySP);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_SP_QuanLyActionPerformed

    private synchronized void mni_NCC_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NCC_QuanLyActionPerformed
        ManHinh_NCC_QuanLy pnl_NCC_QuanLy = null;
        try {
            pnl_NCC_QuanLy = new ManHinh_NCC_QuanLy();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NCC_QuanLy);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NCC_QuanLyActionPerformed

    private synchronized void mni_KH_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_KH_QuanLyActionPerformed
        ManHinh_KH_QuanLy pnl_KH_QuanLy = null;
        try {
            pnl_KH_QuanLy = new ManHinh_KH_QuanLy();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_KH_QuanLy);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_KH_QuanLyActionPerformed

    private synchronized void mni_KH_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_KH_TimKiemActionPerformed
        ManHinh_KH_TimKiem pnl_KH_TimKiem = null;
        try {
            pnl_KH_TimKiem = new ManHinh_KH_TimKiem();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_KH_TimKiem);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_KH_TimKiemActionPerformed

    private synchronized void mni_SP_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_SP_TimKiemActionPerformed
        ManHinh_QA_TimKiem pnl_TimKiemSP = null;
        try {
            pnl_TimKiemSP = new ManHinh_QA_TimKiem();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_TimKiemSP);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();       // TODO add your handling code here:
    }//GEN-LAST:event_mni_SP_TimKiemActionPerformed

    private synchronized void mni_NV_DatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_DatHangActionPerformed
        ManHinh_NV_DatHang pnl_NV_DatHang = null;
        try {
            pnl_NV_DatHang = new ManHinh_NV_DatHang();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_DatHang);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_mni_NV_DatHangActionPerformed

    private synchronized void mni_NV_LapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_LapHoaDonActionPerformed
        ManHinh_NV_LapHoaDon pnl_NV_LapHoaDon = null;
        try {
            pnl_NV_LapHoaDon = new ManHinh_NV_LapHoaDon();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_LapHoaDon);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_LapHoaDonActionPerformed

    private synchronized void mni_NV_ThongKeDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_ThongKeDoanhThuActionPerformed
        ManHinh_NV_ThongKeDoanhThu pnl_NV_ThongKeDoanhThu = null;
        try {
            pnl_NV_ThongKeDoanhThu = new ManHinh_NV_ThongKeDoanhThu();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_ThongKeDoanhThu);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_ThongKeDoanhThuActionPerformed

    private synchronized void mni_NV_ThongKeSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_ThongKeSanPhamActionPerformed
        ManHinh_NV_ThongKeSanPham pnl_NV_ThongKeSanPham = null;
        try {
            pnl_NV_ThongKeSanPham = new ManHinh_NV_ThongKeSanPham();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_ThongKeSanPham);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_ThongKeSanPhamActionPerformed

    private synchronized void mni_NV_ThongKeThongTinKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_ThongKeThongTinKHActionPerformed
        ManHinh_NV_ThongKeThongTinKhachHang pnl_NV_ThongKeThongTinKhachHang = null;
        try {
            pnl_NV_ThongKeThongTinKhachHang = new ManHinh_NV_ThongKeThongTinKhachHang();
        } catch (SQLException | RemoteException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_ThongKeThongTinKhachHang);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_ThongKeThongTinKHActionPerformed

    private synchronized void mni_NV_XemDSHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_XemDSHoaDonActionPerformed
        ManHinh_NV_XemDSHoaDon pnl_NV_XemDSHoaDon = null;
        try {
            pnl_NV_XemDSHoaDon = new ManHinh_NV_XemDSHoaDon();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_XemDSHoaDon);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_XemDSHoaDonActionPerformed

    private synchronized void mni_NV_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_QuanLyActionPerformed
        ManHinh_NV_QuanLy pnl_NV_QuanLy = null;
        try {
            pnl_NV_QuanLy = new ManHinh_NV_QuanLy();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_QuanLy);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_QuanLyActionPerformed

    private synchronized void mni_NV_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_TimKiemActionPerformed
        ManHinh_NV_TimKiem pnl_NV_TimKiem = null;
        try {
            pnl_NV_TimKiem = new ManHinh_NV_TimKiem();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_NV_TimKiem);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_TimKiemActionPerformed

    private synchronized void mni_TK_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_TK_QuanLyActionPerformed
        ManHinh_TaiKhoan_QuanLy pnl_TK_QuanLy = null;
        try {
            pnl_TK_QuanLy = new ManHinh_TaiKhoan_QuanLy();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_TK_QuanLy);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_TK_QuanLyActionPerformed

    private synchronized void mni_NCC_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NCC_TimKiemActionPerformed
        ManHinh_NCC_TimKiem pnl_KH_QuanLy = null;
        try {
            pnl_KH_QuanLy = new ManHinh_NCC_TimKiem();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_KH_QuanLy);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NCC_TimKiemActionPerformed

    private synchronized void mni_SP_KichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_SP_KichThuocActionPerformed
        ManHinh_QA_KichThuoc pnl_QA_KichThuoc = null;
        try {
            pnl_QA_KichThuoc = new ManHinh_QA_KichThuoc();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_QA_KichThuoc);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_SP_KichThuocActionPerformed

    private synchronized void mni_SP_ChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_SP_ChatLieuActionPerformed
        ManHinh_QA_ChatLieu pnl_QA_ChatLieu = null;
        try {
            pnl_QA_ChatLieu = new ManHinh_QA_ChatLieu();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_QA_ChatLieu);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();

    }//GEN-LAST:event_mni_SP_ChatLieuActionPerformed

    private synchronized void mni_SP_MauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_SP_MauSacActionPerformed
        ManHinh_QA_MauSac pnl_QA_MauSac = null;
        try {
            pnl_QA_MauSac = new ManHinh_QA_MauSac();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_QA_MauSac);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_SP_MauSacActionPerformed

    private synchronized void mni_SP_DanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_SP_DanhMucActionPerformed
        ManHinh_QA_DanhMuc pnl_QA_DanhMuc = null;
        try {
            pnl_QA_DanhMuc = new ManHinh_QA_DanhMuc();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_QA_DanhMuc);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_SP_DanhMucActionPerformed

    private synchronized void mni_PK_QuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_PK_QuanLyActionPerformed
        ManHinh_PK_QuanLy pnl_PK_QuanLy = null;
        try {
            pnl_PK_QuanLy = new ManHinh_PK_QuanLy();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_PK_QuanLy);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_PK_QuanLyActionPerformed

    private synchronized void mni_PK_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_PK_TimKiemActionPerformed
        ManHinh_PK_TimKiem pnl_PK_TimKiem = null;
        try {
            pnl_PK_TimKiem = new ManHinh_PK_TimKiem();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnl_PK_TimKiem);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_PK_TimKiemActionPerformed

    private synchronized void mnu_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_DangXuatActionPerformed


    }//GEN-LAST:event_mnu_DangXuatActionPerformed

    private synchronized void mnu_DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnu_DangXuatMouseClicked

        try {
            new Login().setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnu_DangXuatMouseClicked

    private synchronized void mni_NV_HuyDonDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mni_NV_HuyDonDatActionPerformed
        ManHinh_NV_HuyDonDat pnlHinh_NV_HuyDonDat = null;
        try {
            pnlHinh_NV_HuyDonDat = new ManHinh_NV_HuyDonDat();
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException e) {
            throw new RuntimeException(e);
        }
        pnl_GiaoDienChucNang.removeAll();
        pnl_GiaoDienChucNang.add(pnlHinh_NV_HuyDonDat);
        pnl_GiaoDienChucNang.revalidate();
        pnl_GiaoDienChucNang.repaint();
    }//GEN-LAST:event_mni_NV_HuyDonDatActionPerformed

    /**
     * @param args the command line arguments
     */
    public synchronized static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public synchronized void run() {
                try {
                    new HomePage().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem mni_KH_QuanLy;
    private javax.swing.JMenuItem mni_KH_TimKiem;
    private javax.swing.JMenuItem mni_NCC_QuanLy;
    private javax.swing.JMenuItem mni_NCC_TimKiem;
    private javax.swing.JMenuItem mni_NV_DatHang;
    private javax.swing.JMenuItem mni_NV_HuyDonDat;
    private javax.swing.JMenuItem mni_NV_LapHoaDon;
    private javax.swing.JMenuItem mni_NV_QuanLy;
    private javax.swing.JMenuItem mni_NV_ThongKeDoanhThu;
    private javax.swing.JMenuItem mni_NV_ThongKeSanPham;
    private javax.swing.JMenuItem mni_NV_ThongKeThongTinKH;
    private javax.swing.JMenuItem mni_NV_TimKiem;
    private javax.swing.JMenuItem mni_NV_XemDSHoaDon;
    private javax.swing.JMenuItem mni_PK_QuanLy;
    private javax.swing.JMenuItem mni_PK_TimKiem;
    private javax.swing.JMenuItem mni_SP_ChatLieu;
    private javax.swing.JMenuItem mni_SP_DanhMuc;
    private javax.swing.JMenuItem mni_SP_KichThuoc;
    private javax.swing.JMenuItem mni_SP_MauSac;
    private javax.swing.JMenuItem mni_SP_QuanLy;
    private javax.swing.JMenuItem mni_SP_TimKiem;
    private javax.swing.JMenuItem mni_TK_QuanLy;
    private javax.swing.JMenu mnu_DangXuat;
    private javax.swing.JMenu mnu_KhachHang;
    private javax.swing.JMenuBar mnu_ManHinhChinh;
    private javax.swing.JMenu mnu_NhaCungCap;
    private javax.swing.JMenu mnu_NhanVien;
    private javax.swing.JMenu mnu_PhuKien;
    private javax.swing.JMenu mnu_SanPham;
    private javax.swing.JMenu mnu_TaiKhoan;
    private javax.swing.JMenu mnu_TenNVDangNhap;
    public static javax.swing.JPanel pnl_GiaoDienChucNang;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang1;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang2;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang3;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang4;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang5;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang6;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang7;
    private javax.swing.JPopupMenu.Separator spr_NV_ThanhNgang8;
    private javax.swing.JPopupMenu.Separator spr_PK_ThanhNgang;
    private javax.swing.JPopupMenu.Separator spr_SP_ThanhNgang;
    private javax.swing.JPopupMenu.Separator spr_SP_ThanhNgang1;
    private javax.swing.JPopupMenu.Separator spr_SP_ThanhNgang2;
    private javax.swing.JPopupMenu.Separator spr_SP_ThanhNgang3;
    private javax.swing.JPopupMenu.Separator spr_SP_ThanhNgang4;
    private javax.swing.JPopupMenu.Separator spr_ThanhNgang10;
    private javax.swing.JPopupMenu.Separator spr_ThanhNgang9;
    // End of variables declaration//GEN-END:variables
}
