/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fit.iuh.qlbhtt;

import fit.iuh.dao.*;
import fit.iuh.entity.*;
import fit.iuh.util.RMIClientUtil;

import java.io.File;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.awt.Image;
import java.awt.Label;
import java.text.Normalizer;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author DMX
 */
public  class ManHinh_PK_QuanLy extends javax.swing.JPanel {
    private DefaultTableModel modelSanPham;
    private ISanPhamDao dao_SanPham;
    private IChatLieuDao dao_ChatLieu;
    private IKichThuocDao dao_KichThuoc;
    private IMauSacDao dao_MauSac;
    private IPhanLoaiDao dao_PhanLoai;
    private INhaCungCapDao dao_NhaCungCap;
    private File file = null;

    private boolean trangThaiThem = false;
    private boolean trangThaiSua = false;
    
    private boolean ngonNgu = Login.ngonNgu;
    /**
     * Creates new form quanly
     */
    public  ManHinh_PK_QuanLy() throws SQLException, RemoteException {
        dao_SanPham = RMIClientUtil.getSanPhamDao();
        dao_ChatLieu = RMIClientUtil.getChatLieuDao();
        dao_KichThuoc = RMIClientUtil.getKichThuocDao();
        dao_MauSac = RMIClientUtil.getMauSacDao();
        dao_PhanLoai = RMIClientUtil.getPhanLoaiDao();
        dao_NhaCungCap = RMIClientUtil.getNhaCungCapDao();

        initComponents();
        if(!ngonNgu) {
            chuyenDoiNgonNgu();
        }
        tbl_PhuKien.setDefaultEditor(Object.class, null); //Không cho chỉnh sửa cột
        tbl_PhuKien.getTableHeader().setReorderingAllowed(false); //Không cho di chuyển cột
        
        docDuLieuPhuKien();
        docDuLieuCMB();
    }

    public synchronized void chuyenDoiNgonNgu() {
        
        btn_CapNhat.setText("Updates");
        btn_Luu.setText("Save");
        btn_Them.setText("Insert");
        btn_XoaTrang.setText("Erase white");
        btn_ChonAnh.setText("Select photo");
        
        lbl_ChatLieu.setText("Fabric");
        lbl_giaNhap.setText("Import price");
        lbl_GiaBan.setText("Price");
        lbl_HinhAnhSP.setText("Image");        
        lbl_KichThuoc.setText("Size");
        
        lbl_MaPK.setText("Accessories ID");
        lbl_MauSac.setText("Color");
        lbl_NCC.setText("Supplier");

        lbl_NgayNhap.setText("Date Added");
        lbl_PhanLoai.setText("Category");
        lbl_SoLuong.setText("Quantity");
        lbl_TenPK.setText("Accessories Name");       
        
        lbl_TieuDe.setText("ACCESSORICES MANAGEMENT");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private synchronized void initComponents() {

        pnl_DanhSachPhuKien = new javax.swing.JPanel();
        scr_DanhSachPhuKien = new javax.swing.JScrollPane();
        tbl_PhuKien = new javax.swing.JTable();
        pnl_PK_TieuDe = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();
        pnl_ThongTin = new javax.swing.JPanel();
        txt_TenPK = new javax.swing.JTextField();
        txt_MaPK = new javax.swing.JTextField();
        lbl_MaPK = new javax.swing.JLabel();
        lbl_PhanLoai = new javax.swing.JLabel();
        lbl_TenPK = new javax.swing.JLabel();
        lbl_NCC = new javax.swing.JLabel();
        lbl_GiaBan = new javax.swing.JLabel();
        lbl_giaNhap = new javax.swing.JLabel();
        lbl_KichThuoc = new javax.swing.JLabel();
        lbl_MauSac = new javax.swing.JLabel();
        lbl_ChatLieu = new javax.swing.JLabel();
        lbl_SoLuong = new javax.swing.JLabel();
        txt_GiaNhap = new javax.swing.JTextField();
        txt_GiaBan = new javax.swing.JTextField();
        txt_SoLuong = new javax.swing.JTextField();
        pnl_HinhAnhSP = new javax.swing.JPanel();
        lbl_HinhAnhSP = new javax.swing.JLabel();
        cmb_ChatLieu = new javax.swing.JComboBox<>();
        cmb_PhanLoai = new javax.swing.JComboBox<>();
        cmb_MauSac = new javax.swing.JComboBox<>();
        cmb_KichThuoc = new javax.swing.JComboBox<>();
        cmb_NCC = new javax.swing.JComboBox<>();
        btn_ChonAnh = new javax.swing.JButton();
        lbl_NgayNhap = new javax.swing.JLabel();
        dch_NgayNhap = new com.toedter.calendar.JDateChooser();
        pnl_NutChucNang = new javax.swing.JPanel();
        btn_Them = new javax.swing.JButton();
        btn_XoaTrang = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        btn_Luu = new javax.swing.JButton();

        setBackground(new java.awt.Color(199, 210, 213));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        if(ngonNgu){
            scr_DanhSachPhuKien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phụ kiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)));
        } else {
            scr_DanhSachPhuKien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lists of accessories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        }
        scr_DanhSachPhuKien.setPreferredSize(new java.awt.Dimension(750, 196));

        tbl_PhuKien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        if(ngonNgu) {
            tbl_PhuKien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Mã phụ kiện", "Tên phụ kiện", "Phân loại", "Giá bán ", "Giá nhập", "Ngày nhập", "Kích cỡ", "Màu sắc", "Chất liệu", "Nhà cung cấp", "Số lượng tồn"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public synchronized Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
        } else {
            tbl_PhuKien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Accessories ID", "Accessories name", "Catagory", "Price", "Import price", "Date added", "Size", "Color", "Fabric", "Supplier", "Quantity"

                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public synchronized Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
        }
        tbl_PhuKien.setRowHeight(35);
        tbl_PhuKien.setShowGrid(true);
        tbl_PhuKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tbl_PhuKienMouseClicked(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        scr_DanhSachPhuKien.setViewportView(tbl_PhuKien);

        lbl_TieuDe.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        lbl_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe.setText("QUẢN LÝ PHỤ KIỆN");
        lbl_TieuDe.setMaximumSize(new java.awt.Dimension(32767, 32767));
        lbl_TieuDe.setPreferredSize(new java.awt.Dimension(181, 40));

        javax.swing.GroupLayout pnl_PK_TieuDeLayout = new javax.swing.GroupLayout(pnl_PK_TieuDe);
        pnl_PK_TieuDe.setLayout(pnl_PK_TieuDeLayout);
        pnl_PK_TieuDeLayout.setHorizontalGroup(
            pnl_PK_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PK_TieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_PK_TieuDeLayout.setVerticalGroup(
            pnl_PK_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_DanhSachPhuKienLayout = new javax.swing.GroupLayout(pnl_DanhSachPhuKien);
        pnl_DanhSachPhuKien.setLayout(pnl_DanhSachPhuKienLayout);
        pnl_DanhSachPhuKienLayout.setHorizontalGroup(
            pnl_DanhSachPhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_PK_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_DanhSachPhuKienLayout.setVerticalGroup(
            pnl_DanhSachPhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DanhSachPhuKienLayout.createSequentialGroup()
                .addComponent(pnl_PK_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        pnl_ThongTin.setBackground(new java.awt.Color(199, 210, 213));
        if(ngonNgu) {
            pnl_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phụ kiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)));
        } else {
            pnl_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accessory information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        }
        pnl_ThongTin.setPreferredSize(new java.awt.Dimension(1400, 300));

        txt_TenPK.setEditable(false);
        txt_TenPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TenPK.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenPKActionPerformed(evt);
            }
        });

        txt_MaPK.setEditable(false);
        txt_MaPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MaPK.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaPKActionPerformed(evt);
            }
        });

        lbl_MaPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MaPK.setText("Mã phụ kiện");

        lbl_PhanLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PhanLoai.setText("Phân loại");

        lbl_TenPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_TenPK.setText("Tên phụ kiện");

        lbl_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NCC.setText("Nhà cung cấp");

        lbl_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_GiaBan.setText("Giá bán");

        lbl_giaNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_giaNhap.setText("Giá nhập");

        lbl_KichThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_KichThuoc.setText("Kích thước");

        lbl_MauSac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MauSac.setText("Màu sắc");

        lbl_ChatLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ChatLieu.setText("Chất liệu");

        lbl_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SoLuong.setText("Số lượng");

        txt_GiaNhap.setEditable(false);
        txt_GiaNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_GiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaNhapActionPerformed(evt);
            }
        });

        txt_GiaBan.setEditable(false);
        txt_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_GiaBan.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaBanActionPerformed(evt);
            }
        });

        txt_SoLuong.setEditable(false);
        txt_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoLuongActionPerformed(evt);
            }
        });

        pnl_HinhAnhSP.setBackground(new java.awt.Color(255, 255, 255));
        pnl_HinhAnhSP.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        pnl_HinhAnhSP.setMaximumSize(new java.awt.Dimension(175, 141));
        pnl_HinhAnhSP.setMinimumSize(new java.awt.Dimension(175, 141));
        pnl_HinhAnhSP.setPreferredSize(new java.awt.Dimension(175, 141));

        lbl_HinhAnhSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_HinhAnhSP.setText("Hình Ảnh");
        lbl_HinhAnhSP.setMaximumSize(new java.awt.Dimension(175, 141));
        lbl_HinhAnhSP.setMinimumSize(new java.awt.Dimension(175, 141));
        lbl_HinhAnhSP.setPreferredSize(new java.awt.Dimension(175, 141));

        javax.swing.GroupLayout pnl_HinhAnhSPLayout = new javax.swing.GroupLayout(pnl_HinhAnhSP);
        pnl_HinhAnhSP.setLayout(pnl_HinhAnhSPLayout);
        pnl_HinhAnhSPLayout.setHorizontalGroup(
            pnl_HinhAnhSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_HinhAnhSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_HinhAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_HinhAnhSPLayout.setVerticalGroup(
            pnl_HinhAnhSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HinhAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );

        cmb_ChatLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_ChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton" }));

        cmb_PhanLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_PhanLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Áo" }));

        cmb_MauSac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_MauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng" }));

        cmb_KichThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_KichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L" }));

        cmb_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_NCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CT THHH Hades" }));

        btn_ChonAnh.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_ChonAnh.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-picture-30.png")); // NOI18N
        btn_ChonAnh.setText("Chọn Ảnh");
        btn_ChonAnh.setBorder(null);
        btn_ChonAnh.setEnabled(false);
        btn_ChonAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ChonAnhMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ChonAnhMouseExited(evt);
            }
        });
        btn_ChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonAnhActionPerformed(evt);
            }
        });

        lbl_NgayNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NgayNhap.setText("Ngày nhập");

        dch_NgayNhap.setDateFormatString("dd-MM-yyyy");
        dch_NgayNhap.setEnabled(false);

        javax.swing.GroupLayout pnl_ThongTinLayout = new javax.swing.GroupLayout(pnl_ThongTin);
        pnl_ThongTin.setLayout(pnl_ThongTinLayout);
        pnl_ThongTinLayout.setHorizontalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl_PhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_PhanLoai, 0, 242, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(50, 50, 50)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_GiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_GiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(lbl_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(pnl_HinhAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dch_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );
        pnl_ThongTinLayout.setVerticalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dch_NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ThongTinLayout.createSequentialGroup()
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_GiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_PhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_PhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_ChonAnh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_HinhAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        txt_MaPK.getAccessibleContext().setAccessibleName("");

        pnl_NutChucNang.setBackground(new java.awt.Color(199, 210, 213));
        if(ngonNgu) {
            pnl_NutChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)));
        } else {
            pnl_NutChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Function", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)));
        }

        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_Them.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-add-30.png")); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.setBorder(null);
        btn_Them.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ThemMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ThemMouseExited(evt);
            }
        });
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_XoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_XoaTrang.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-delete-document-30.png")); // NOI18N
        btn_XoaTrang.setText("Xóa trắng");
        btn_XoaTrang.setBorder(null);
        btn_XoaTrang.setPreferredSize(new java.awt.Dimension(80, 30));
        btn_XoaTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_XoaTrangMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_XoaTrangMouseExited(evt);
            }
        });
        btn_XoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn_XoaTrangActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_CapNhat.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-update-30.png")); // NOI18N
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.setBorder(null);
        btn_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseExited(evt);
            }
        });
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        btn_Luu.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_Luu.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-save-30.png")); // NOI18N
        btn_Luu.setText("Lưu");
        btn_Luu.setBorder(null);
        btn_Luu.setEnabled(false);
        btn_Luu.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LuuMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LuuMouseExited(evt);
            }
        });
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_NutChucNangLayout = new javax.swing.GroupLayout(pnl_NutChucNang);
        pnl_NutChucNang.setLayout(pnl_NutChucNangLayout);
        pnl_NutChucNangLayout.setHorizontalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addGroup(pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_XoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_NutChucNangLayout.setVerticalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_XoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnl_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private synchronized void txt_TenPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenPKActionPerformed

    private synchronized void txt_MaPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaPKActionPerformed

    private synchronized void txt_GiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaNhapActionPerformed

    private synchronized void txt_GiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaBanActionPerformed

    private synchronized void txt_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoLuongActionPerformed

    private synchronized void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
        int row = tbl_PhuKien.getSelectedRow();
        if(row!=-1){
            if(btn_CapNhat.getText().equalsIgnoreCase("Cập nhật")) {
                trangThaiSua = true;
                // Vo hieu or kich hoat chuc nang
                btn_CapNhat.setText("Hủy");
                btn_Them.setEnabled(false);
                btn_Luu.setEnabled(true);
                // Kich hoat chinh sua
                txt_TenPK.setEditable(true);
                txt_SoLuong.setEditable(true);
                txt_GiaBan.setEditable(true);
                txt_GiaNhap.setEditable(true);
                btn_ChonAnh.setEnabled(true);            
                cmb_ChatLieu.setEditable(true);
                cmb_KichThuoc.setEditable(true);
                cmb_MauSac.setEditable(true);
                cmb_PhanLoai.setEditable(true);
                cmb_NCC.setEditable(true);
            } else if(btn_CapNhat.getText().equalsIgnoreCase("Hủy")) {
                trangThaiThem = false;
                trangThaiSua = false;
                // Vo hieu or kich hoat chuc nang
                btn_CapNhat.setText("Cập nhật");
                btn_Them.setEnabled(true);
                btn_CapNhat.setEnabled(true);
                btn_Luu.setEnabled(false);
                xoaTrang();
                // Vo hieu chinh sua
                txt_TenPK.setEditable(false);
                txt_SoLuong.setEditable(false);
                txt_GiaBan.setEditable(false);
                txt_GiaNhap.setEditable(false);
                cmb_ChatLieu.setEditable(false);
                cmb_KichThuoc.setEditable(false);
                cmb_MauSac.setEditable(false);
                cmb_PhanLoai.setEditable(false);
                cmb_NCC.setEditable(false);
            }
        }else
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần cập nhật!");
    }//GEN-LAST:event_btn_CapNhatActionPerformed
    
    private static String removeAccent(String s) { 
        String temp = Normalizer.normalize(s, Normalizer.Form.NFD); 
        Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+"); 
        return pattern.matcher(temp).replaceAll(""); 
    } 
    
    private boolean validData() { 
        String tenSP = txt_TenPK.getText().trim();
        String soLuong = txt_SoLuong.getText().trim(); 
        String giaNhap = txt_GiaNhap.getText().trim(); 
        String giaBan = txt_GiaBan.getText().trim();
        if (file == null) {
            if(trangThaiSua == false){                
                // kiem tra da co anh chua 
                JOptionPane.showMessageDialog(this, "Phải chọn ảnh cho sản phẩm"); 
                return false; 
            }
        }
        if (!(tenSP.length() > 0 && tenSP.matches("[\\p{L}\\s']+"))) {
            // Chu cai dau phai viet hoa va khong duoc rong 
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không hợp lệ"); 
            txt_TenPK.requestFocus(); 
            return false; 
        } 
        if (soLuong.length() > 0) {
            // khong duoc rong 
            try { 
                int sl = Integer.parseInt(soLuong);
                if (sl < 0) { 
                    JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                    txt_SoLuong.requestFocus(); 
                    return false; 
                } 
            } catch (NumberFormatException ex) { // phai la ky tu so 
                JOptionPane.showMessageDialog(this, "Số lượng phải là số"); 
                return false; 
            } 
        } else { 
            JOptionPane.showMessageDialog(this, "Số lượng không được rỗng");
            txt_SoLuong.requestFocus(); 
            return false; 
        } 
        if (giaNhap.length() > 0) { // khong duoc rong 
            try { 
                Double gn = Double.parseDouble(giaNhap);
                if (gn <= 0) { 
                    JOptionPane.showMessageDialog(this, "Giá nhập phải lớn hơn 0");
                    txt_GiaNhap.requestFocus(); 
                    return false; 
                } 
            } catch (NumberFormatException ex) { // phai la ky tu so 
                JOptionPane.showMessageDialog(this, "Giá nhập phải là số"); 
                return false; 
            } 
        } else { 
            JOptionPane.showMessageDialog(this, "Giá nhập không được rỗng"); 
            txt_GiaNhap.requestFocus(); 
            return false; 
        }
        if (giaBan.length() > 0) { // khong duoc rong 
            try { 
                Double gb = Double.parseDouble(giaBan);
                if (gb <= 0) { 
                    JOptionPane.showMessageDialog(this, "Giá bán phải lớn hơn 0");
                    txt_GiaBan.requestFocus(); 
                    return false; 
                } 
            } catch (NumberFormatException ex) { // phai la ky tu so 
                JOptionPane.showMessageDialog(this, "Giá bán phải là số"); 
                return false; 
            } 
        } else { 
            JOptionPane.showMessageDialog(this, "Giá bán không được rỗng"); 
            txt_GiaBan.requestFocus(); 
            return false; 
        } 
        if (dch_NgayNhap.getDate().after(new Date())) {
            JOptionPane.showMessageDialog(this, "Ngày nhập hàng phải trước ngày hiện tại");
            dch_NgayNhap.setDate(new Date());
            return false;
        }
        return true;
    }
    
    private synchronized void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        if(trangThaiThem) {
            if (validData()) {
                try {
                    xuLyThemSanPham();
                    JOptionPane.showMessageDialog(this, "Thêm thành công!");
                    
                    trangThaiThem = false;
                    trangThaiSua = false;
                    // Vo hieu or kich hoat chuc nang
                    btn_Them.setText("Thêm");
                    btn_Them.setEnabled(true);
                    btn_CapNhat.setEnabled(true);
                    btn_XoaTrang.setEnabled(false);
                    btn_Luu.setEnabled(false);
                    xoaTrang();
                    // Vo hieu chinh sua
                    txt_TenPK.setEditable(false);
                    txt_SoLuong.setEditable(false);
                    txt_GiaBan.setEditable(false);
                    txt_GiaNhap.setEditable(false);
                    dch_NgayNhap.setEnabled(false);
                    btn_ChonAnh.setEnabled(false);
                    cmb_ChatLieu.setEditable(false);
                    cmb_KichThuoc.setEditable(false);
                    cmb_MauSac.setEditable(false);
                    cmb_PhanLoai.setEditable(false);
                    cmb_NCC.setEditable(false);
                } catch (ParseException ex) {
                    Logger.getLogger(ManHinh_QA_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        } else if(trangThaiSua){
            if (validData()) {
                try {
                    xuLyCapNhatSanPham();
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                    
                    trangThaiThem = false;
                    trangThaiSua = false;
                    // Vo hieu or kich hoat chuc nang
                    btn_CapNhat.setText("Cập nhật");
                    btn_Them.setEnabled(true);
                    btn_CapNhat.setEnabled(true);
                    btn_XoaTrang.setEnabled(true);
                    btn_Luu.setEnabled(false);
                    xoaTrang();
                    // Vo hieu chinh sua
                    txt_TenPK.setEditable(false);
                    txt_SoLuong.setEditable(false);
                    txt_GiaBan.setEditable(false);
                    txt_GiaNhap.setEditable(false);
                    dch_NgayNhap.setEnabled(false);
                    btn_ChonAnh.setEnabled(false);
                    cmb_ChatLieu.setEditable(false);
                    cmb_KichThuoc.setEditable(false);
                    cmb_MauSac.setEditable(false);
                    cmb_PhanLoai.setEditable(false);
                    cmb_NCC.setEditable(false);
                } catch (ParseException ex) {
                    Logger.getLogger(ManHinh_QA_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        }
    }//GEN-LAST:event_btn_LuuActionPerformed

    private synchronized void btn_ChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonAnhActionPerformed
        JFileChooser filechoose = new JFileChooser("data/");
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("hinh anh", "jpg", "png");
        filechoose.setFileFilter(imageFilter);
        filechoose.setMultiSelectionEnabled(false);

        int x = filechoose.showDialog(this, "Chọn Ảnh");
        if (x == JFileChooser.APPROVE_OPTION) {
            file = filechoose.getSelectedFile();
            lbl_HinhAnhSP.setText("");
            lbl_HinhAnhSP.setIcon(ResizeImage(file.getAbsolutePath(), file.getName()));
        }
    }//GEN-LAST:event_btn_ChonAnhActionPerformed

    private synchronized void btn_ThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseEntered
         if(btn_Them.isEnabled()) {
            btn_Them.setBackground(new Color(0x9EDDFF));
            btn_Them.setForeground(new Color(0x141E46));
       }
    }//GEN-LAST:event_btn_ThemMouseEntered

    private synchronized void btn_ThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMouseExited
        if(btn_Them.isEnabled()) {
            btn_Them.setBackground(UIManager.getColor("Menu.background"));
            btn_Them.setForeground(UIManager.getColor("Menu.foreground"));
        }
    }//GEN-LAST:event_btn_ThemMouseExited

    private synchronized void btn_CapNhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseEntered
        if(btn_CapNhat.isEnabled()) {
        btn_CapNhat.setBackground(new Color(0x9EDDFF));
       btn_CapNhat.setForeground(new Color(0x141E46));}
    }//GEN-LAST:event_btn_CapNhatMouseEntered

    private synchronized void btn_CapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseExited
        if(btn_CapNhat.isEnabled()) {
        btn_CapNhat.setBackground(UIManager.getColor("Menu.background"));
        btn_CapNhat.setForeground(UIManager.getColor("Menu.foreground"));}
    }//GEN-LAST:event_btn_CapNhatMouseExited

    private synchronized void btn_LuuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LuuMouseEntered
        if(btn_Luu.isEnabled()) {
        btn_Luu.setBackground(new Color(0x9EDDFF));
       btn_Luu.setForeground(new Color(0x141E46));}
    }//GEN-LAST:event_btn_LuuMouseEntered

    private synchronized void btn_LuuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LuuMouseExited
        if(btn_Luu.isEnabled()) {
        btn_Luu.setBackground(UIManager.getColor("Menu.background"));
        btn_Luu.setForeground(UIManager.getColor("Menu.foreground"));}
    }//GEN-LAST:event_btn_LuuMouseExited

    private synchronized void btn_ChonAnhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ChonAnhMouseEntered
        if(btn_ChonAnh.isEnabled()) {
            btn_ChonAnh.setBackground(new Color(0x9EDDFF));
            btn_ChonAnh.setForeground(new Color(0x141E46));
       }
    }//GEN-LAST:event_btn_ChonAnhMouseEntered

    private synchronized void btn_ChonAnhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ChonAnhMouseExited
        if(btn_ChonAnh.isEnabled()) {
            btn_ChonAnh.setBackground(UIManager.getColor("Menu.background"));
            btn_ChonAnh.setForeground(UIManager.getColor("Menu.foreground"));
        }
    }//GEN-LAST:event_btn_ChonAnhMouseExited

    private synchronized void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        if(btn_Them.getText().equalsIgnoreCase("Thêm")) {
            trangThaiThem = true;
            // Vo hieu or kich hoat chuc nang
            btn_Them.setText("Hủy");
            btn_CapNhat.setEnabled(false);
            btn_XoaTrang.setEnabled(false);
            btn_Luu.setEnabled(true);
            // Kich hoat chinh sua
            txt_TenPK.setEditable(true);
            txt_SoLuong.setEditable(true);
            txt_GiaBan.setEditable(true);
            txt_GiaNhap.setEditable(true);
            dch_NgayNhap.setEnabled(true);
            btn_ChonAnh.setEnabled(true);            
            cmb_ChatLieu.setEditable(true);
            cmb_KichThuoc.setEditable(true);
            cmb_MauSac.setEditable(true);
            cmb_PhanLoai.setEditable(true);
            cmb_NCC.setEditable(true);
            xoaTrang();
        } else if(btn_Them.getText().equalsIgnoreCase("Hủy")) {
            trangThaiThem = false;
            trangThaiSua = false;
            // Vo hieu or kich hoat chuc nang
            btn_Them.setText("Thêm");
            btn_Them.setEnabled(true);
            btn_CapNhat.setEnabled(true);
            btn_XoaTrang.setEnabled(true);
            btn_Luu.setEnabled(false);
            xoaTrang();
            // Vo hieu chinh sua
            txt_TenPK.setEditable(false);
            txt_SoLuong.setEditable(false);
            txt_GiaBan.setEditable(false);
            txt_GiaNhap.setEditable(false);
            dch_NgayNhap.setEnabled(false);
            btn_ChonAnh.setEnabled(false);
            cmb_ChatLieu.setEditable(false);
            cmb_KichThuoc.setEditable(false);
            cmb_MauSac.setEditable(false);
            cmb_PhanLoai.setEditable(false);
            cmb_NCC.setEditable(false);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private synchronized void tbl_PhuKienMouseClicked(java.awt.event.MouseEvent evt) throws RemoteException {//GEN-FIRST:event_tbl_PhuKienMouseClicked
        int row =  tbl_PhuKien.getSelectedRow();
        if(row!=-1) {
           //Load thong tin vao txt, combobox        
           SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
           Date ngayNhap = null;
            try {
                ngayNhap = sdf.parse(tbl_PhuKien.getValueAt(row, 5).toString());
            } catch (ParseException ex) {
                Logger.getLogger(ManHinh_QA_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }
           
           long maSanPham = Long.parseLong(tbl_PhuKien.getValueAt(row, 0).toString());
           SanPham sanPham = dao_SanPham.getSanPhamTheoMa(maSanPham);
           
           txt_MaPK.setText(tbl_PhuKien.getValueAt(row, 0).toString());
           txt_TenPK.setText(tbl_PhuKien.getValueAt(row, 1).toString());
           cmb_PhanLoai.setSelectedItem(tbl_PhuKien.getValueAt(row, 2).toString());
           txt_GiaBan.setText(tbl_PhuKien.getValueAt(row, 3).toString());
           txt_GiaNhap.setText(tbl_PhuKien.getValueAt(row, 4).toString()); 
           dch_NgayNhap.setDate(ngayNhap);
           cmb_KichThuoc.setSelectedItem(tbl_PhuKien.getValueAt(row, 6).toString());
           cmb_MauSac.setSelectedItem(tbl_PhuKien.getValueAt(row, 7).toString());
           cmb_ChatLieu.setSelectedItem(tbl_PhuKien.getValueAt(row, 8).toString());
           cmb_NCC.setSelectedItem(tbl_PhuKien.getValueAt(row, 9).toString());
           txt_SoLuong.setText(tbl_PhuKien.getValueAt(row, 10).toString());
           //Load hinh anh
           
           
           File file = new File("");
           String path= file.getAbsolutePath();
           String imagePath = path + "/data/" + sanPham.getHinhAnh();
           File imageFile = new File(imagePath);

           //ImageIcon imageIcon = new ImageIcon(imagePath);
           //imageIcon.setDescription("" + sanPham.getHinhAnh()); // Đặt mô tả cho ImageIcon

            lbl_HinhAnhSP.setIcon(ResizeImage(imagePath, sanPham.getHinhAnh()));
           //System.out.println("Path: " + path);
           //lbl_HinhAnhSP.setIcon(ResizeImage(path + "/data/"+sanPham.getHinhAnh()));
       }
    }//GEN-LAST:event_tbl_PhuKienMouseClicked

    private synchronized void btn_XoaTrangActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_btn_XoaTrangActionPerformed
        xoaTrang();
        docDuLieuPhuKien();
    }//GEN-LAST:event_btn_XoaTrangActionPerformed

    private synchronized void btn_XoaTrangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTrangMouseExited
        if(btn_XoaTrang.isEnabled()) {
            btn_XoaTrang.setBackground(UIManager.getColor("Menu.background"));
            btn_XoaTrang.setForeground(UIManager.getColor("Menu.foreground"));
        }
    }//GEN-LAST:event_btn_XoaTrangMouseExited

    private synchronized void btn_XoaTrangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTrangMouseEntered
        if(btn_XoaTrang.isEnabled()) {
            btn_XoaTrang.setBackground(new Color(0x9EDDFF));
            btn_XoaTrang.setForeground(new Color(0x141E46));
        }
    }//GEN-LAST:event_btn_XoaTrangMouseEntered

    public synchronized ImageIcon ResizeImage(String imgPath, String desc){
        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(pnl_HinhAnhSP.getWidth(), pnl_HinhAnhSP.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        image.setDescription(desc);
        return image;
    }
    
    private synchronized void xuLyThemSanPham() throws ParseException, RemoteException {
        //Get and add data
        String tenQA = txt_TenPK.getText();
        String soLuong = txt_SoLuong.getText();
        String giaBan = txt_GiaBan.getText();
        String giaNhap = txt_GiaNhap.getText();
        
        Date ngayNhap = dch_NgayNhap.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String ngayNhapString = sdf.format(ngayNhap);

        String hinhAnh = file.getName();
        ChatLieu chatLieu = dao_ChatLieu.getChatLieuTheoTen(cmb_ChatLieu.getSelectedItem().toString());
        KichThuoc kichThuoc = dao_KichThuoc.getKichThuocTheoTen(cmb_KichThuoc.getSelectedItem().toString());
        MauSac mauSac = dao_MauSac.getMauSacTheoTen(cmb_MauSac.getSelectedItem().toString());
        PhanLoai phanLoai = dao_PhanLoai.getPhanLoaiTheoTen(cmb_PhanLoai.getSelectedItem().toString());
        NhaCungCap nhaCungCap = dao_NhaCungCap.getNhaCungCapTheoTen( cmb_NCC.getSelectedItem().toString());
        SanPham sanPham = new SanPham(tenQA, Integer.parseInt(soLuong), Double.parseDouble(giaBan), Double.parseDouble(giaNhap), sdf.parse(ngayNhapString), hinhAnh, chatLieu, kichThuoc, mauSac, phanLoai, nhaCungCap);
        dao_SanPham.themSanPham(sanPham);
        //Add vao model tren giao dien
        modelSanPham = (DefaultTableModel) tbl_PhuKien.getModel();
        Object[] object = new Object[11];
            object[0] = sanPham.getMaSP();
            object[1] = sanPham.getTenSP();
            object[2] = phanLoai.getLoaiSanPham();
            object[3] = NumberFormat.getInstance().format( sanPham.getGiaBan());
            object[4] = NumberFormat.getInstance().format( sanPham.getGiaNhap());
            object[5] = ngayNhapString;
            object[6] = kichThuoc.getKichThuoc();
            object[7] = mauSac.getMauSac();
            object[8] = chatLieu.getChatLieu();
            object[9] = nhaCungCap.getTenNCC();
            object[10] = sanPham.getSoLuong();
        modelSanPham.addRow(object);
        docDuLieuPhuKien();
    }
    
    private synchronized void xuLyCapNhatSanPham() throws ParseException, RemoteException {
        int row = tbl_PhuKien.getSelectedRow();
        if(row!=-1){
            //Get and update data
            long maQA = Long.parseLong(txt_MaPK.getText());
            String tenQA = txt_TenPK.getText();
            String soLuong = txt_SoLuong.getText();
            String giaBan = txt_GiaBan.getText();
            String giaNhap = txt_GiaNhap.getText();

            Date ngayNhap = dch_NgayNhap.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String ngayNhapString = sdf.format(ngayNhap);

            Icon labelIcon = lbl_HinhAnhSP.getIcon();
            String hinhAnh = ((ImageIcon) labelIcon).getDescription();
            System.out.println("Tên hình ảnh: " + hinhAnh);
            
            //String hinhAnh = file.getName();
            ChatLieu chatLieu = dao_ChatLieu.getChatLieuTheoTen(cmb_ChatLieu.getSelectedItem().toString());
            KichThuoc kichThuoc = dao_KichThuoc.getKichThuocTheoTen(cmb_KichThuoc.getSelectedItem().toString());
            MauSac mauSac = dao_MauSac.getMauSacTheoTen(cmb_MauSac.getSelectedItem().toString());
            PhanLoai phanLoai = dao_PhanLoai.getPhanLoaiTheoTen(cmb_PhanLoai.getSelectedItem().toString());
            NhaCungCap nhaCungCap = dao_NhaCungCap.getNhaCungCapTheoTen( cmb_NCC.getSelectedItem().toString());
            SanPham sanPham = new SanPham(maQA ,tenQA, Integer.parseInt(soLuong), Double.parseDouble(giaBan), Double.parseDouble(giaNhap), sdf.parse(ngayNhapString), hinhAnh, chatLieu, kichThuoc, mauSac, phanLoai, nhaCungCap);
            dao_SanPham.capNhatSanPham(sanPham);
            //Chỉnh sửa trên model
            tbl_PhuKien.setValueAt(sanPham.getTenSP(), row, 1);
            tbl_PhuKien.setValueAt(phanLoai.getLoaiSanPham(), row, 2);
            tbl_PhuKien.setValueAt(sanPham.getGiaBan(), row, 3);
            tbl_PhuKien.setValueAt(sanPham.getGiaNhap(), row, 4);
            tbl_PhuKien.setValueAt(ngayNhapString, row, 5);
            tbl_PhuKien.setValueAt(kichThuoc.getKichThuoc(), row, 6);
            tbl_PhuKien.setValueAt(mauSac.getMauSac(), row, 7);
            tbl_PhuKien.setValueAt(chatLieu.getChatLieu(), row, 8);
            tbl_PhuKien.setValueAt(nhaCungCap.getTenNCC(), row, 9);
            tbl_PhuKien.setValueAt(sanPham.getSoLuong(), row, 10);
        }else
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần cập nhật!");
    }
    
    private synchronized void xuLyXoaSanPham() throws RemoteException {
        int row = tbl_PhuKien.getSelectedRow();
        if(row!=-1){
             if(JOptionPane.showConfirmDialog(this, "Bạn có chắc là xóa dòng này không?", "Cảnh Báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                 long maSP = Long.parseLong(txt_MaPK.getText());
                 dao_SanPham.xoaSanPham(maSP);
                 modelSanPham.removeRow(row);
                 JOptionPane.showMessageDialog(this, "Xóa thành công");
                 xoaTrang();
             }
         } else {
             JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa!");
         }
    }
    
    public synchronized void xoaTrang() {
        txt_MaPK.setText("");
        txt_TenPK.setText("");
        txt_GiaBan.setText("");
        txt_GiaNhap.setText("");
        lbl_HinhAnhSP.setIcon(null);
        txt_SoLuong.setText("");
        cmb_ChatLieu.setSelectedIndex(0);
        cmb_KichThuoc.setSelectedIndex(0);
        cmb_MauSac.setSelectedIndex(0);
        cmb_PhanLoai.setSelectedIndex(0);
        cmb_NCC.setSelectedIndex(0);
        file = null;
        tbl_PhuKien.clearSelection();
    }
    
    public synchronized void docDuLieuPhuKien() throws RemoteException {
        
        modelSanPham = (DefaultTableModel) tbl_PhuKien.getModel();
        modelSanPham.setRowCount(0);
        for(SanPham pk: dao_SanPham.getAllPhuKien()) {

            PhanLoai pl = dao_PhanLoai.getDLPhanLoaiSPTheoMa(pk.getPhanLoai().getMaPhanLoai());
            KichThuoc kt = dao_KichThuoc.getDLKichThuocTheoMa(pk.getKichThuoc().getMaKichThuoc());
            MauSac ms = dao_MauSac.getDLMauSacTheoMa(pk.getMauSac().getMaMauSac());
            ChatLieu cl = dao_ChatLieu.getDLChatLieuTheoMa(pk.getChatLieu().getMaChatLieu());
            NhaCungCap ncc = dao_NhaCungCap.getNhaCungCapTheoMa(pk.getNhaCungCap().getMaNCC());

            Object[] object = new Object[11];
            object[0] = pk.getMaSP();
            object[1] = pk.getTenSP();
            object[2] = pl.getLoaiSanPham();
            object[3] = NumberFormat.getInstance().format( pk.getGiaBan());
            object[4] = NumberFormat.getInstance().format( pk.getGiaNhap());
            object[5] = pk.getNgayNhap();
            object[6] = kt.getKichThuoc();
            object[7] = ms.getMauSac();
            object[8] = cl.getChatLieu();
            object[9] = ncc.getTenNCC();
            object[10] = pk.getSoLuong();
            modelSanPham.addRow(object);
        }
    }
    
    public synchronized void docDuLieuCMB() throws RemoteException {
        //Doc du lieu ComboBox chat lieu
        ArrayList<ChatLieu> ds_ChatLieu = new ArrayList<>();
        ds_ChatLieu = dao_ChatLieu.getAllChatLieu();
        
        cmb_ChatLieu.removeAllItems();
        for (ChatLieu chatLieu : ds_ChatLieu) {
            cmb_ChatLieu.addItem(chatLieu.getChatLieu());
        }
        
        //Doc du lieu ComboBox kich thuoc
        ArrayList<KichThuoc> ds_KichThuoc = new ArrayList<>();
        ds_KichThuoc = dao_KichThuoc.getAllKichThuoc();
        
        cmb_KichThuoc.removeAllItems();
        for (KichThuoc kichThuoc : ds_KichThuoc) {
            cmb_KichThuoc.addItem(kichThuoc.getKichThuoc());
        }
        
        //Doc du lieu ComboBox mau sac
        ArrayList<MauSac> ds_MauSac = new ArrayList<>();
        ds_MauSac = dao_MauSac.getAllMauSac();
        
        cmb_MauSac.removeAllItems();
        for (MauSac mauSac : ds_MauSac) {
            cmb_MauSac.addItem(mauSac.getMauSac());
        }
        
        //Doc du lieu ComboBox phan loai
        ArrayList<PhanLoai> ds_PhanLoai = new ArrayList<>();
        ds_PhanLoai = dao_PhanLoai.getAllPhanLoaiCuaPhuKien();
        
        cmb_PhanLoai.removeAllItems();
        for (PhanLoai phanLoai : ds_PhanLoai) {
            cmb_PhanLoai.addItem(phanLoai.getLoaiSanPham());
        }
        
        //Doc du lieu ComboBox nha cung cap
        ArrayList<NhaCungCap> ds_NhaCungCap = new ArrayList<>();
        ds_NhaCungCap = dao_NhaCungCap.getAllNhaCungCap();
        
        cmb_NCC.removeAllItems();
        for (NhaCungCap nhaCungCap : ds_NhaCungCap) {
            cmb_NCC.addItem(nhaCungCap.getTenNCC());
        }
        
        dch_NgayNhap.setDate(new Date());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_ChonAnh;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_XoaTrang;
    private javax.swing.JComboBox<String> cmb_ChatLieu;
    private javax.swing.JComboBox<String> cmb_KichThuoc;
    private javax.swing.JComboBox<String> cmb_MauSac;
    private javax.swing.JComboBox<String> cmb_NCC;
    private javax.swing.JComboBox<String> cmb_PhanLoai;
    private com.toedter.calendar.JDateChooser dch_NgayNhap;
    private javax.swing.JLabel lbl_ChatLieu;
    private javax.swing.JLabel lbl_GiaBan;
    private javax.swing.JLabel lbl_HinhAnhSP;
    private javax.swing.JLabel lbl_KichThuoc;
    private javax.swing.JLabel lbl_MaPK;
    private javax.swing.JLabel lbl_MauSac;
    private javax.swing.JLabel lbl_NCC;
    private javax.swing.JLabel lbl_NgayNhap;
    private javax.swing.JLabel lbl_PhanLoai;
    private javax.swing.JLabel lbl_SoLuong;
    private javax.swing.JLabel lbl_TenPK;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JLabel lbl_giaNhap;
    private javax.swing.JPanel pnl_DanhSachPhuKien;
    private javax.swing.JPanel pnl_HinhAnhSP;
    private javax.swing.JPanel pnl_NutChucNang;
    private javax.swing.JPanel pnl_PK_TieuDe;
    private javax.swing.JPanel pnl_ThongTin;
    private javax.swing.JScrollPane scr_DanhSachPhuKien;
    private javax.swing.JTable tbl_PhuKien;
    private javax.swing.JTextField txt_GiaBan;
    private javax.swing.JTextField txt_GiaNhap;
    private javax.swing.JTextField txt_MaPK;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_TenPK;
    // End of variables declaration//GEN-END:variables
}
