/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fit.iuh.qlbhtt;

import fit.iuh.dao.*;
import fit.iuh.entity.*;
import fit.iuh.util.RMIClientUtil;

import java.awt.Color;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DMX
 */
public  class ManHinh_NV_HuyDonDat extends javax.swing.JPanel {
    private DefaultTableModel modelPhieuDatHang;
    private DefaultTableModel modelCTPhieuDatHang;
    private IPhieuDatHangDao dao_PhieuDatHang;
    private ICTPhieuDatHangDao dao_CTPhieuDatHang;
    private INhanVienDao dao_NhanVien;
    private IKhachHangDao dao_KhachHang;
    private ISanPhamDao dao_SanPham;
    /**
     * Creates new form quanly
     */
    public  ManHinh_NV_HuyDonDat() throws SQLException, RemoteException {
        dao_SanPham = RMIClientUtil.getSanPhamDao();
        dao_PhieuDatHang = RMIClientUtil.getPhieuDatHangDao();
        dao_CTPhieuDatHang = RMIClientUtil.getCtPhieuDatHangDao();
        dao_NhanVien = RMIClientUtil.getNhanVienDao();
        dao_KhachHang = RMIClientUtil.getKhachHangDao();
        initComponents();
        
        modelCTPhieuDatHang = (DefaultTableModel) tbl_CTPhieuDatHang.getModel();
        
        tbl_PhieuDatHang.setDefaultEditor(Object.class, null); //Không cho chỉnh sửa cột
        tbl_PhieuDatHang.getTableHeader().setReorderingAllowed(false); //Không cho di chuyển cột
        
        tbl_CTPhieuDatHang.setDefaultEditor(Object.class, null); //Không cho chỉnh sửa cột
        tbl_CTPhieuDatHang.getTableHeader().setReorderingAllowed(false); //Không cho di chuyển cột
        
//      Lần đầu chạy chương trình, load dữ liệu vào bảng
        docDuLieuPhieuDatHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private synchronized void initComponents() {

        pnl_DanhSachPhieuDatHang = new javax.swing.JPanel();
        scr_DanhSachPhieuDatHang = new javax.swing.JScrollPane();
        tbl_PhieuDatHang = new javax.swing.JTable();
        pnl_NV_HuyDonDat = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();
        scr_DanhSachCTPhieuDatHang = new javax.swing.JScrollPane();
        tbl_CTPhieuDatHang = new javax.swing.JTable();
        pnl_ThongTin = new javax.swing.JPanel();
        txt_NgayLap = new javax.swing.JTextField();
        txt_MaPDT = new javax.swing.JTextField();
        lbl_MaPDT = new javax.swing.JLabel();
        lbl_NgayLap = new javax.swing.JLabel();
        lbl_MaKH = new javax.swing.JLabel();
        lbl_MaNV = new javax.swing.JLabel();
        lbl_TenNV = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        txt_TenNV = new javax.swing.JTextField();
        txt_MaKH = new javax.swing.JTextField();
        txt_SDTKH = new javax.swing.JTextField();
        lbl_TenKH = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        lbl_SDTKH = new javax.swing.JLabel();
        pnl_NutChucNang = new javax.swing.JPanel();
        btn_HuyDonDat = new javax.swing.JButton();

        setBackground(new java.awt.Color(199, 210, 213));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        scr_DanhSachPhieuDatHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phiếu đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_PhieuDatHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_PhieuDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu đặt hàng", "Mã nhân viên", "Tên nhân viên", "Mã khách hàng", "Tên khách hàng", "SDT khách hàng", "Ngày lập"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public synchronized Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_PhieuDatHang.setRowHeight(35);
        tbl_PhieuDatHang.setShowGrid(true);
        tbl_PhieuDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tbl_PhieuDatHangMouseClicked(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        scr_DanhSachPhieuDatHang.setViewportView(tbl_PhieuDatHang);
        if (tbl_PhieuDatHang.getColumnModel().getColumnCount() > 0) {
            tbl_PhieuDatHang.getColumnModel().getColumn(5).setHeaderValue("SDT khách hàng");
            tbl_PhieuDatHang.getColumnModel().getColumn(6).setHeaderValue("Ngày lập");
        }

        lbl_TieuDe.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        lbl_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe.setText("HỦY ĐƠN ĐẶT");
        lbl_TieuDe.setMaximumSize(new java.awt.Dimension(32767, 32767));
        lbl_TieuDe.setPreferredSize(new java.awt.Dimension(181, 40));

        javax.swing.GroupLayout pnl_NV_HuyDonDatLayout = new javax.swing.GroupLayout(pnl_NV_HuyDonDat);
        pnl_NV_HuyDonDat.setLayout(pnl_NV_HuyDonDatLayout);
        pnl_NV_HuyDonDatLayout.setHorizontalGroup(
            pnl_NV_HuyDonDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NV_HuyDonDatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, 1219, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_NV_HuyDonDatLayout.setVerticalGroup(
            pnl_NV_HuyDonDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        scr_DanhSachCTPhieuDatHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết phiếu đặt hàng tương ứng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_CTPhieuDatHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_CTPhieuDatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu đặt hàng", "Mã sản phẩm", "Tên sản phẩm", "Số lượng mua", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public synchronized Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_CTPhieuDatHang.setRowHeight(35);
        tbl_CTPhieuDatHang.setShowGrid(true);
        tbl_CTPhieuDatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CTPhieuDatHangMouseClicked(evt);
            }
        });
        scr_DanhSachCTPhieuDatHang.setViewportView(tbl_CTPhieuDatHang);

        javax.swing.GroupLayout pnl_DanhSachPhieuDatHangLayout = new javax.swing.GroupLayout(pnl_DanhSachPhieuDatHang);
        pnl_DanhSachPhieuDatHang.setLayout(pnl_DanhSachPhieuDatHangLayout);
        pnl_DanhSachPhieuDatHangLayout.setHorizontalGroup(
            pnl_DanhSachPhieuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_NV_HuyDonDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_DanhSachPhieuDatHangLayout.createSequentialGroup()
                .addComponent(scr_DanhSachPhieuDatHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_DanhSachCTPhieuDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_DanhSachPhieuDatHangLayout.setVerticalGroup(
            pnl_DanhSachPhieuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DanhSachPhieuDatHangLayout.createSequentialGroup()
                .addComponent(pnl_NV_HuyDonDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl_DanhSachPhieuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_DanhSachPhieuDatHangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scr_DanhSachPhieuDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                    .addGroup(pnl_DanhSachPhieuDatHangLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(scr_DanhSachCTPhieuDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
        );

        pnl_ThongTin.setBackground(new java.awt.Color(199, 210, 213));
        pnl_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txt_NgayLap.setEditable(false);
        txt_NgayLap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_NgayLap.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NgayLapActionPerformed(evt);
            }
        });

        txt_MaPDT.setEditable(false);
        txt_MaPDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MaPDT.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaPDTActionPerformed(evt);
            }
        });

        lbl_MaPDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MaPDT.setText("Mã phiếu đặt hàng");

        lbl_NgayLap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NgayLap.setText("Ngày lập");

        lbl_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MaKH.setText("Mã khách hàng");

        lbl_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MaNV.setText("Mã nhân viên");

        lbl_TenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_TenNV.setText("Tên nhân viên");

        txt_MaNV.setEditable(false);
        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MaNV.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaNVActionPerformed(evt);
            }
        });

        txt_TenNV.setEditable(false);
        txt_TenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TenNV.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenNVActionPerformed(evt);
            }
        });

        txt_MaKH.setEditable(false);
        txt_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_SDTKH.setEditable(false);
        txt_SDTKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_TenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_TenKH.setText("Tên khách hàng");

        txt_TenKH.setEditable(false);
        txt_TenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_SDTKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SDTKH.setText("SDT khách hàng");

        javax.swing.GroupLayout pnl_ThongTinLayout = new javax.swing.GroupLayout(pnl_ThongTin);
        pnl_ThongTin.setLayout(pnl_ThongTinLayout);
        pnl_ThongTinLayout.setHorizontalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MaPDT, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaPDT)
                    .addComponent(lbl_NgayLap))
                .addGap(50, 50, 50)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ThongTinLayout.setVerticalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MaPDT, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaPDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TenKH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_SDTKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pnl_NutChucNang.setBackground(new java.awt.Color(199, 210, 213));
        pnl_NutChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btn_HuyDonDat.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-delete-document-30.png")); // NOI18N
        btn_HuyDonDat.setText("Hủy đơn đặt");
        btn_HuyDonDat.setBorder(null);
        btn_HuyDonDat.setMinimumSize(new java.awt.Dimension(20, 30));
        btn_HuyDonDat.setPreferredSize(new java.awt.Dimension(20, 30));
        btn_HuyDonDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HuyDonDatMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HuyDonDatMouseExited(evt);
            }
        });
        btn_HuyDonDat.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn_HuyDonDatActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout pnl_NutChucNangLayout = new javax.swing.GroupLayout(pnl_NutChucNang);
        pnl_NutChucNang.setLayout(pnl_NutChucNangLayout);
        pnl_NutChucNangLayout.setHorizontalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btn_HuyDonDat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnl_NutChucNangLayout.setVerticalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_HuyDonDat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnl_DanhSachPhieuDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_DanhSachPhieuDatHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private synchronized void txt_NgayLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NgayLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NgayLapActionPerformed

    private synchronized void txt_MaPDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaPDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaPDTActionPerformed

    private synchronized void txt_MaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaNVActionPerformed

    private synchronized void txt_TenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenNVActionPerformed

    private synchronized void btn_HuyDonDatActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_btn_HuyDonDatActionPerformed
        xuLyXoaPhieuDatHang();
        
    }//GEN-LAST:event_btn_HuyDonDatActionPerformed

    private synchronized void tbl_PhieuDatHangMouseClicked(java.awt.event.MouseEvent evt) throws RemoteException {//GEN-FIRST:event_tbl_PhieuDatHangMouseClicked
        int row =  tbl_PhieuDatHang.getSelectedRow();
       if(row!=-1) {
           //Đổ dữ liệu vào panel_ThongTin
           txt_MaPDT.setText(tbl_PhieuDatHang.getValueAt(row, 0).toString());
           txt_NgayLap.setText(tbl_PhieuDatHang.getValueAt(row, 6).toString());
           txt_MaNV.setText(tbl_PhieuDatHang.getValueAt(row, 1).toString());
           txt_TenNV.setText(tbl_PhieuDatHang.getValueAt(row, 2).toString());
           txt_MaKH.setText(tbl_PhieuDatHang.getValueAt(row, 3).toString()); 
           txt_TenKH.setText(tbl_PhieuDatHang.getValueAt(row, 4).toString());
           txt_SDTKH.setText(tbl_PhieuDatHang.getValueAt(row, 5).toString());
           //Đổ dữ liệu vào CTPhieuDatHang tương ứng
           DefaultTableModel modelCTPDH = (DefaultTableModel) tbl_CTPhieuDatHang.getModel();
           modelCTPDH.setRowCount(0);
           ArrayList<CTPhieuDatHang> listCTPDH = dao_CTPhieuDatHang.getAllCTPhieuDatHang(Long.parseLong(tbl_PhieuDatHang.getValueAt(row, 0).toString()));
           for (CTPhieuDatHang cTPhieuDatHang : listCTPDH) {

               SanPham sp = dao_SanPham.getSanPhamTheoMa(cTPhieuDatHang.getSanPham().getMaSP());
               PhieuDatHang pdh = dao_PhieuDatHang.getPDTTheoMa(cTPhieuDatHang.getPhieuDatHang().getMaPhieuDat());
               Object[] object = new Object[5];
                object[0] = pdh.getMaPhieuDat();
                object[1] = sp.getMaSP();
                object[2] = sp.getTenSP();
                object[3] = cTPhieuDatHang.getSoLuong();
                object[4] = sp.getGiaBan() * cTPhieuDatHang.getSoLuong();
                modelCTPDH.addRow(object);
           }
       }
    }//GEN-LAST:event_tbl_PhieuDatHangMouseClicked

    private synchronized void btn_HuyDonDatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HuyDonDatMouseEntered
         if(btn_HuyDonDat.isEnabled()) {
            btn_HuyDonDat.setBackground(new Color(0x9EDDFF));
            btn_HuyDonDat.setForeground(new Color(0x141E46));
        }
    }//GEN-LAST:event_btn_HuyDonDatMouseEntered

    private synchronized void btn_HuyDonDatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HuyDonDatMouseExited
        if(btn_HuyDonDat.isEnabled()) {
            btn_HuyDonDat.setBackground(UIManager.getColor("Menu.background"));
            btn_HuyDonDat.setForeground(UIManager.getColor("Menu.foreground"));
        }
    }//GEN-LAST:event_btn_HuyDonDatMouseExited

    private synchronized void tbl_CTPhieuDatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CTPhieuDatHangMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_CTPhieuDatHangMouseClicked

    
    /**
     * Xóa trắng các Jtext filed
     */
    public synchronized void xoaTrangTxt() {
        txt_NgayLap.setText("");
        txt_MaKH.setText("");
        txt_TenKH.setText("");
        txt_SDTKH.setText("");
        txt_MaNV.setText("");
        txt_TenNV.setText("");
        txt_MaPDT.setText("");
    }
    
    /**
     * Load dữ liệu vào bảng
     */
     public synchronized void docDuLieuPhieuDatHang() throws RemoteException {
        modelPhieuDatHang = (DefaultTableModel) tbl_PhieuDatHang.getModel();
        for(PhieuDatHang pdt: dao_PhieuDatHang.getAllPhieuDatHang()) {

            NhanVien nv = dao_NhanVien.getNhanVienTheoMa(pdt.getNhanVien().getMaNV());
            KhachHang kh = dao_KhachHang.getKhachHangTheoMa(pdt.getKhachHang().getMaKH());

            Object[] object = new Object[7];
            object[0] = pdt.getMaPhieuDat();
            object[1] = nv.getMaNV();
            object[2] = nv.getHoTen();
            object[3] = kh.getMaKH();
            object[4] = kh.getHoTen();
            object[5] = kh.getSdt();
            object[6] = pdt.getNgayLap().toString();
            modelPhieuDatHang.addRow(object);
        }
    }
     public synchronized void xuLyXoaCTPhieuDatHang(long maPDT) throws RemoteException {
         //Hoàn trả số lượng mua thành số lượng tồn
//         ArrayList<CTPhieuDatHang> list_CTPDT = dao_CTPhieuDatHang.getAllCTPhieuDatHang(maPDT);
//         for (CTPhieuDatHang cTPhieuDatHang : list_CTPDT) {
//             dao_SanPham.tangSoLuongSanPham(cTPhieuDatHang.getSanPham().getMaSP(), cTPhieuDatHang.getSoLuong());
//         }
         //Xoa CTPhieuDatHang
         dao_CTPhieuDatHang.xoaCTPhieuDatHang(maPDT);
         modelCTPhieuDatHang.setRowCount(0);
     }
     /**
      * Xử lý xóa Nhà Cung Cấp
      */
     public synchronized void xuLyXoaPhieuDatHang() throws RemoteException {
         int row = tbl_PhieuDatHang.getSelectedRow();
         if(row!=-1) {
             if(JOptionPane.showConfirmDialog(this, "Bạn có chắc là xóa đơn đặt này không?", "Cảnh Báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                 long maPhieuDatHang = Long.parseLong(txt_MaPDT.getText());
                 xuLyXoaCTPhieuDatHang(maPhieuDatHang);
                 dao_PhieuDatHang.xoaPhieuDatHang(maPhieuDatHang);
                 modelPhieuDatHang.removeRow(row);
                 JOptionPane.showMessageDialog(this, "Hủy đơn đặt thành công");
                 xoaTrangTxt();
             }
         } else {
             JOptionPane.showMessageDialog(this, "Vui lòng chọn đơn đặt cần xóa trong danh sách phiếu đặt hàng!");
         }
     }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_HuyDonDat;
    private javax.swing.JLabel lbl_MaKH;
    private javax.swing.JLabel lbl_MaNV;
    private javax.swing.JLabel lbl_MaPDT;
    private javax.swing.JLabel lbl_NgayLap;
    private javax.swing.JLabel lbl_SDTKH;
    private javax.swing.JLabel lbl_TenKH;
    private javax.swing.JLabel lbl_TenNV;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JPanel pnl_DanhSachPhieuDatHang;
    private javax.swing.JPanel pnl_NV_HuyDonDat;
    private javax.swing.JPanel pnl_NutChucNang;
    private javax.swing.JPanel pnl_ThongTin;
    private javax.swing.JScrollPane scr_DanhSachCTPhieuDatHang;
    private javax.swing.JScrollPane scr_DanhSachPhieuDatHang;
    private javax.swing.JTable tbl_CTPhieuDatHang;
    private javax.swing.JTable tbl_PhieuDatHang;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_MaPDT;
    private javax.swing.JTextField txt_NgayLap;
    private javax.swing.JTextField txt_SDTKH;
    private javax.swing.JTextField txt_TenKH;
    private javax.swing.JTextField txt_TenNV;
    // End of variables declaration//GEN-END:variables
}
