/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fit.iuh.qlbhtt;


import fit.iuh.dao.*;

import fit.iuh.entity.*;
import fit.iuh.util.RMIClientUtil;

import java.io.File;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.awt.Image;
import java.awt.Label;
import java.text.Normalizer;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import java.awt.Color;
import java.text.NumberFormat;
import javax.swing.UIManager;

/**
 *
 * @author DMX
 */
public  class ManHinh_PK_TimKiem extends javax.swing.JPanel {

    private DefaultTableModel modelSanPham;
    private ISanPhamDao dao_SanPham;
    private IChatLieuDao dao_ChatLieu;
    private IKichThuocDao dao_KichThuoc;
    private IMauSacDao dao_MauSac;
    private IPhanLoaiDao dao_PhanLoai;
    private INhaCungCapDao dao_NhaCungCap;
    private File file = null;
    private boolean ngonNgu = Login.ngonNgu;
    /**
     * Creates new form quanly
     */
    public  ManHinh_PK_TimKiem() throws SQLException, RemoteException {
        dao_SanPham = RMIClientUtil.getSanPhamDao();
        dao_ChatLieu = RMIClientUtil.getChatLieuDao();
        dao_KichThuoc = RMIClientUtil.getKichThuocDao();
        dao_MauSac = RMIClientUtil.getMauSacDao();
        dao_PhanLoai = RMIClientUtil.getPhanLoaiDao();
        dao_NhaCungCap = RMIClientUtil.getNhaCungCapDao();

        initComponents();
        if(!ngonNgu) {
            chuyenDoiNgonNgu();
        }
        tbl_PhuKien.setDefaultEditor(Object.class, null); //Không cho chỉnh sửa cột
        tbl_PhuKien.getTableHeader().setReorderingAllowed(false); //Không cho di chuyển cột

        docDuLieuPhuKien();
        docDuLieuCMB();
    }
    
    public synchronized void chuyenDoiNgonNgu() {
        
       
        btn_XoaTrang.setText("Erase white");
        btn_TimKiem.setText("Search");
        lbl_ChatLieu.setText("Fabric");
        lbl_GiaNhap.setText("Import price");
        lbl_GiaBan.setText("Price");
        lbl_HinhAnhSP.setText("Image");        
        lbl_KichThuoc.setText("Size");
        
        lbl_MaPK.setText("Clothing ID");
        lbl_MauSac.setText("Color");
        lbl_NCC.setText("Supplier");

        lbl_NgayNhap.setText("Date Added");
        lbl_PhanLoai.setText("Category");
        lbl_SoLuong.setText("Quantity");
        lbl_TenPK.setText("Clothing Name");       
        
        lbl_TieuDe.setText(" SEARCH FOR ACCESSORY");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private synchronized  void initComponents() {

        pnl_DanhSachPhuKien = new javax.swing.JPanel();
        scr_DanhSachPhuKien = new javax.swing.JScrollPane();
        tbl_PhuKien = new javax.swing.JTable();
        pnl_PK_TieuDe = new javax.swing.JPanel();
        lbl_TieuDe = new javax.swing.JLabel();
        pnl_ThongTin = new javax.swing.JPanel();
        txt_TenPK = new javax.swing.JTextField();
        txt_MaPK = new javax.swing.JTextField();
        lbl_MaPK = new javax.swing.JLabel();
        lbl_PhanLoai = new javax.swing.JLabel();
        lbl_TenPK = new javax.swing.JLabel();
        lbl_NCC = new javax.swing.JLabel();
        lbl_GiaBan = new javax.swing.JLabel();
        lbl_GiaNhap = new javax.swing.JLabel();
        lbl_KichThuoc = new javax.swing.JLabel();
        lbl_MauSac = new javax.swing.JLabel();
        lbl_ChatLieu = new javax.swing.JLabel();
        lbl_SoLuong = new javax.swing.JLabel();
        txt_GiaNhap = new javax.swing.JTextField();
        txt_GiaBan = new javax.swing.JTextField();
        txt_SoLuong = new javax.swing.JTextField();
        pnl_HinhAnhSanPham = new javax.swing.JPanel();
        lbl_HinhAnhSP = new javax.swing.JLabel();
        cmb_ChatLieu = new javax.swing.JComboBox<>();
        cmb_PhanLoai = new javax.swing.JComboBox<>();
        cmb_MauSac = new javax.swing.JComboBox<>();
        cmb_KichThuoc = new javax.swing.JComboBox<>();
        cmb_NCC = new javax.swing.JComboBox<>();
        dch_NgayNhap = new com.toedter.calendar.JDateChooser();
        lbl_NgayNhap = new javax.swing.JLabel();
        pnl_NutChucNang = new javax.swing.JPanel();
        btn_TimKiem = new javax.swing.JButton();
        btn_XoaTrang = new javax.swing.JButton();

        setBackground(new java.awt.Color(199, 210, 213));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        if(ngonNgu) {
            scr_DanhSachPhuKien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phụ kiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        } else {
            scr_DanhSachPhuKien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lists of Accessories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        }

        tbl_PhuKien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        if(ngonNgu){
            tbl_PhuKien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Mã phụ kiện", "Tên phụ kiện", "Phân loại", "Giá bán ", "Giá nhập", "Ngày nhập", "Kích cỡ", "Màu sắc", "Chất liệu", "Nhà cung cấp", "Số lượng tồn"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public synchronized Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
        } else {
            tbl_PhuKien.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Accessories ID", "Accessories name", "Catagory", "Price", "Import price", "Date added", "Size", "Color", "Fabric", "Supplier", "Quantity"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public synchronized Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
        }
        tbl_PhuKien.setRowHeight(35);
        tbl_PhuKien.setShowGrid(true);
        tbl_PhuKien.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tbl_PhuKienMouseClicked(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        scr_DanhSachPhuKien.setViewportView(tbl_PhuKien);

        lbl_TieuDe.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        lbl_TieuDe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe.setText("TÌM KIẾM PHỤ KIỆN");
        lbl_TieuDe.setMaximumSize(new java.awt.Dimension(32767, 32767));
        lbl_TieuDe.setPreferredSize(new java.awt.Dimension(181, 40));

        javax.swing.GroupLayout pnl_PK_TieuDeLayout = new javax.swing.GroupLayout(pnl_PK_TieuDe);
        pnl_PK_TieuDe.setLayout(pnl_PK_TieuDeLayout);
        pnl_PK_TieuDeLayout.setHorizontalGroup(
            pnl_PK_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_PK_TieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_PK_TieuDeLayout.setVerticalGroup(
            pnl_PK_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_DanhSachPhuKienLayout = new javax.swing.GroupLayout(pnl_DanhSachPhuKien);
        pnl_DanhSachPhuKien.setLayout(pnl_DanhSachPhuKienLayout);
        pnl_DanhSachPhuKienLayout.setHorizontalGroup(
            pnl_DanhSachPhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, 1365, Short.MAX_VALUE)
            .addComponent(pnl_PK_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_DanhSachPhuKienLayout.setVerticalGroup(
            pnl_DanhSachPhuKienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DanhSachPhuKienLayout.createSequentialGroup()
                .addComponent(pnl_PK_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );

        pnl_ThongTin.setBackground(new java.awt.Color(199, 210, 213));
        if(ngonNgu){
            pnl_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phụ kiện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        } else {
            pnl_ThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Accessory informationn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        }
        pnl_ThongTin.setPreferredSize(new java.awt.Dimension(1438, 300));

        txt_TenPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TenPK.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenPKActionPerformed(evt);
            }
        });

        txt_MaPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MaPK.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaPKActionPerformed(evt);
            }
        });

        lbl_MaPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MaPK.setText("Mã phụ kiện");

        lbl_PhanLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PhanLoai.setText("Phân loại");

        lbl_TenPK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_TenPK.setText("Tên phụ kiện");

        lbl_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NCC.setText("Nhà cung cấp");

        lbl_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_GiaBan.setText("Giá bán");

        lbl_GiaNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_GiaNhap.setText("Giá nhập");

        lbl_KichThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_KichThuoc.setText("Kích thước");

        lbl_MauSac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MauSac.setText("Màu sắc");

        lbl_ChatLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ChatLieu.setText("Chất liệu");

        lbl_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_SoLuong.setText("Số lượng");

        txt_GiaNhap.setEditable(false);
        txt_GiaNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_GiaNhap.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaNhapActionPerformed(evt);
            }
        });

        txt_GiaBan.setEditable(false);
        txt_GiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_GiaBan.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaBanActionPerformed(evt);
            }
        });

        txt_SoLuong.setEditable(false);
        txt_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_SoLuong.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SoLuongActionPerformed(evt);
            }
        });

        pnl_HinhAnhSanPham.setBackground(new java.awt.Color(255, 255, 255));
        pnl_HinhAnhSanPham.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        pnl_HinhAnhSanPham.setMaximumSize(new java.awt.Dimension(175, 141));
        pnl_HinhAnhSanPham.setMinimumSize(new java.awt.Dimension(175, 141));

        lbl_HinhAnhSP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_HinhAnhSP.setMaximumSize(new java.awt.Dimension(173, 141));
        lbl_HinhAnhSP.setMinimumSize(new java.awt.Dimension(173, 141));

        javax.swing.GroupLayout pnl_HinhAnhSanPhamLayout = new javax.swing.GroupLayout(pnl_HinhAnhSanPham);
        pnl_HinhAnhSanPham.setLayout(pnl_HinhAnhSanPhamLayout);
        pnl_HinhAnhSanPhamLayout.setHorizontalGroup(
            pnl_HinhAnhSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HinhAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
        );
        pnl_HinhAnhSanPhamLayout.setVerticalGroup(
            pnl_HinhAnhSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_HinhAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );

        cmb_ChatLieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_ChatLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton" }));

        cmb_PhanLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_PhanLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Áo" }));

        cmb_MauSac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_MauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trắng" }));

        cmb_KichThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_KichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L" }));

        cmb_NCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_NCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CT THHH Hades" }));
        cmb_NCC.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_NCCActionPerformed(evt);
            }
        });

        dch_NgayNhap.setEnabled(false);

        lbl_NgayNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NgayNhap.setText("Ngày nhập");

        javax.swing.GroupLayout pnl_ThongTinLayout = new javax.swing.GroupLayout(pnl_ThongTin);
        pnl_ThongTin.setLayout(pnl_ThongTinLayout);
        pnl_ThongTinLayout.setHorizontalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_PhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_PhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_GiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addComponent(lbl_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_GiaNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_GiaNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dch_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addComponent(pnl_HinhAnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl_ThongTinLayout.setVerticalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addComponent(lbl_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_KichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_TenPK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_MauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_GiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_GiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_PhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_GiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_PhanLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                        .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_MaPK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_NCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                                .addComponent(lbl_NgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dch_NgayNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_HinhAnhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pnl_NutChucNang.setBackground(new java.awt.Color(199, 210, 213));
        if(ngonNgu){
            pnl_NutChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        } else {
            pnl_NutChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Function", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        }

        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_TimKiem.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-search-30.png")); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.setBorder(null);
        btn_TimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_TimKiemMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_TimKiemMouseExited(evt);
            }
        });
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn_TimKiemActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        btn_XoaTrang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_XoaTrang.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-delete-30.png")); // NOI18N
        btn_XoaTrang.setText("Xóa trắng");
        btn_XoaTrang.setBorder(null);
        btn_XoaTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_XoaTrangMouseEntered(evt);
            }
            public synchronized void mouseExited(java.awt.event.MouseEvent evt) {
                btn_XoaTrangMouseExited(evt);
            }
        });
        btn_XoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public synchronized void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn_XoaTrangActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout pnl_NutChucNangLayout = new javax.swing.GroupLayout(pnl_NutChucNang);
        pnl_NutChucNang.setLayout(pnl_NutChucNangLayout);
        pnl_NutChucNangLayout.setHorizontalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnl_NutChucNangLayout.setVerticalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_XoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnl_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_DanhSachPhuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private synchronized  void txt_TenPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenPKActionPerformed

    private synchronized  void txt_MaPKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaPKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaPKActionPerformed

    private synchronized  void txt_GiaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaNhapActionPerformed

    private synchronized  void txt_GiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaBanActionPerformed

    private synchronized  void txt_SoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SoLuongActionPerformed

    private synchronized  void btn_TimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimKiemMouseEntered
        btn_TimKiem.setBackground(new Color(0x9EDDFF));
        btn_TimKiem.setForeground(new Color(0x141E46));
    }//GEN-LAST:event_btn_TimKiemMouseEntered

    private synchronized  void btn_TimKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimKiemMouseExited
        btn_TimKiem.setBackground(UIManager.getColor("Menu.background"));
        btn_TimKiem.setForeground(UIManager.getColor("Menu.foreground"));
    }//GEN-LAST:event_btn_TimKiemMouseExited

    private synchronized  void btn_XoaTrangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTrangMouseEntered
        btn_XoaTrang.setBackground(new Color(0x9EDDFF));
        btn_XoaTrang.setForeground(new Color(0x141E46));
    }//GEN-LAST:event_btn_XoaTrangMouseEntered

    private synchronized  void btn_XoaTrangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTrangMouseExited
        btn_XoaTrang.setBackground(UIManager.getColor("Menu.background"));
        btn_XoaTrang.setForeground(UIManager.getColor("Menu.foreground"));
    }//GEN-LAST:event_btn_XoaTrangMouseExited

    private synchronized  void cmb_NCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_NCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_NCCActionPerformed

    private synchronized  void tbl_PhuKienMouseClicked(java.awt.event.MouseEvent evt) throws RemoteException {//GEN-FIRST:event_tbl_PhuKienMouseClicked
        // TODO add your handling code here:
        int row = tbl_PhuKien.getSelectedRow();
        if (row != -1) {
            //Load thong tin vao txt, combobox        
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date ngayNhap = null;
            try {
                ngayNhap = sdf.parse(tbl_PhuKien.getValueAt(row, 5).toString());
            } catch (ParseException ex) {
                Logger.getLogger(ManHinh_QA_QuanLy.class.getName()).log(Level.SEVERE, null, ex);
            }

            long maSanPham = Long.parseLong(tbl_PhuKien.getValueAt(row, 0).toString());
            SanPham sanPham = dao_SanPham.getSanPhamTheoMa(maSanPham);

            txt_MaPK.setText(tbl_PhuKien.getValueAt(row, 0).toString());
            txt_TenPK.setText(tbl_PhuKien.getValueAt(row, 1).toString());
            cmb_PhanLoai.setSelectedItem(tbl_PhuKien.getValueAt(row, 2).toString());
            txt_GiaBan.setText(tbl_PhuKien.getValueAt(row, 3).toString());
            txt_GiaNhap.setText(tbl_PhuKien.getValueAt(row, 4).toString());
            dch_NgayNhap.setDate(ngayNhap);
            cmb_KichThuoc.setSelectedItem(tbl_PhuKien.getValueAt(row, 6).toString());
            cmb_MauSac.setSelectedItem(tbl_PhuKien.getValueAt(row, 7).toString());
            cmb_ChatLieu.setSelectedItem(tbl_PhuKien.getValueAt(row, 8).toString());
            cmb_NCC.setSelectedItem(tbl_PhuKien.getValueAt(row, 9).toString());
            txt_SoLuong.setText(tbl_PhuKien.getValueAt(row, 10).toString());
            //Load hinh anh

            File file = new File("");
            String path = file.getAbsolutePath();
            String imagePath = path + "/data/" + sanPham.getHinhAnh();
            File imageFile = new File(imagePath);

            //ImageIcon imageIcon = new ImageIcon(imagePath);
            //imageIcon.setDescription("" + sanPham.getHinhAnh()); // Đặt mô tả cho ImageIcon
            lbl_HinhAnhSP.setIcon(ResizeImage(imagePath, sanPham.getHinhAnh()));
        }
    }//GEN-LAST:event_tbl_PhuKienMouseClicked

    private synchronized  void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_btn_TimKiemActionPerformed
        xuLyTiemKiemPhuKien();
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private synchronized  void btn_XoaTrangActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_btn_XoaTrangActionPerformed
        // TODO add your handling code here:
        xoaTrang();
        docDuLieuPhuKien();
    }//GEN-LAST:event_btn_XoaTrangActionPerformed

    public synchronized ImageIcon ResizeImage(String imgPath, String desc) {
        ImageIcon myImage = new ImageIcon(imgPath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(pnl_HinhAnhSanPham.getWidth(), pnl_HinhAnhSanPham.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        image.setDescription(desc);
        return image;
    }

    public synchronized void xoaTrang() {
        txt_MaPK.setText("");
        txt_TenPK.setText("");
        txt_GiaBan.setText("");
        txt_GiaNhap.setText("");
        lbl_HinhAnhSP.setIcon(null);
        txt_SoLuong.setText("");
        cmb_ChatLieu.setSelectedIndex(0);
        cmb_KichThuoc.setSelectedIndex(0);
        cmb_MauSac.setSelectedIndex(0);
        cmb_PhanLoai.setSelectedIndex(0);
        cmb_NCC.setSelectedIndex(0);
    }

    private synchronized  void xuLyTiemKiemPhuKien() throws RemoteException {
        String spCN = null;
        if(txt_MaPK.getText().equals("")) {
            spCN = "0";
        } else {
            spCN = txt_MaPK.getText();
        }
        long maSP = Long.parseLong(spCN);
        String tenSP = txt_TenPK.getText();
        String tenPhanLoai = cmb_PhanLoai.getSelectedItem().toString();
        String tenNCC = cmb_NCC.getSelectedItem().toString();
        String tenMauSac = cmb_MauSac.getSelectedItem().toString();
        String tenChatLieu = cmb_ChatLieu.getSelectedItem().toString();
        String tenKichThuoc = cmb_KichThuoc.getSelectedItem().toString();

        DefaultTableModel model = (DefaultTableModel) tbl_PhuKien.getModel();

        ArrayList<SanPham> listSanPham = dao_SanPham.timKiemPhuKien(maSP, tenSP, tenPhanLoai, tenNCC, tenMauSac, tenChatLieu, tenKichThuoc);

        if (listSanPham != null) {
            model.setRowCount(0);
            for (SanPham qa : listSanPham) {

                PhanLoai pl = dao_PhanLoai.getDLPhanLoaiSPTheoMa(qa.getPhanLoai().getMaPhanLoai());
                KichThuoc kt = dao_KichThuoc.getDLKichThuocTheoMa(qa.getKichThuoc().getMaKichThuoc());
                MauSac ms = dao_MauSac.getDLMauSacTheoMa(qa.getMauSac().getMaMauSac());
                ChatLieu cl = dao_ChatLieu.getDLChatLieuTheoMa(qa.getChatLieu().getMaChatLieu());
                NhaCungCap ncc = dao_NhaCungCap.getNhaCungCapTheoMa(qa.getNhaCungCap().getMaNCC());

                Object[] object = new Object[11];
                object[0] = qa.getMaSP();
                object[1] = qa.getTenSP();
                object[2] = pl.getLoaiSanPham();
                object[3] = NumberFormat.getInstance().format(qa.getGiaBan());
                object[4] = NumberFormat.getInstance().format(qa.getGiaNhap());
                object[5] = qa.getNgayNhap();
                object[6] = kt.getKichThuoc();
                object[7] = ms.getMauSac();
                object[8] = cl.getChatLieu();
                object[9] = ncc.getTenNCC();
                object[10] = qa.getSoLuong();
                model.addRow(object);
            }
        } else {
            docDuLieuPhuKien();
        }

        xoaTrang();
    }

    public synchronized void docDuLieuPhuKien() throws RemoteException {
        modelSanPham = (DefaultTableModel) tbl_PhuKien.getModel();
        for (SanPham pk : dao_SanPham.getAllPhuKien()) {

            PhanLoai pl = dao_PhanLoai.getDLPhanLoaiSPTheoMa(pk.getPhanLoai().getMaPhanLoai());
            KichThuoc kt = dao_KichThuoc.getDLKichThuocTheoMa(pk.getKichThuoc().getMaKichThuoc());
            MauSac ms = dao_MauSac.getDLMauSacTheoMa(pk.getMauSac().getMaMauSac());
            ChatLieu cl = dao_ChatLieu.getDLChatLieuTheoMa(pk.getChatLieu().getMaChatLieu());
            NhaCungCap ncc = dao_NhaCungCap.getNhaCungCapTheoMa(pk.getNhaCungCap().getMaNCC());

            Object[] object = new Object[11];
            object[0] = pk.getMaSP();
            object[1] = pk.getTenSP();
            object[2] = pl.getLoaiSanPham();
            object[3] = NumberFormat.getInstance().format(pk.getGiaBan());
            object[4] = NumberFormat.getInstance().format(pk.getGiaNhap());
            object[5] = pk.getNgayNhap();
            object[6] = kt.getKichThuoc();
            object[7] = ms.getMauSac();
            object[8] = cl.getChatLieu();
            object[9] = ncc.getTenNCC();
            object[10] = pk.getSoLuong();
            modelSanPham.addRow(object);
        }
    }

    public synchronized void docDuLieuCMB() throws RemoteException {
        //Doc du lieu ComboBox chat lieu
        ArrayList<ChatLieu> ds_ChatLieu = new ArrayList<>();
        ds_ChatLieu = dao_ChatLieu.getAllChatLieu();

        cmb_ChatLieu.removeAllItems();
        cmb_ChatLieu.addItem("");
        for (ChatLieu chatLieu : ds_ChatLieu) {
            cmb_ChatLieu.addItem(chatLieu.getChatLieu());
        }

        //Doc du lieu ComboBox kich thuoc
        ArrayList<KichThuoc> ds_KichThuoc = new ArrayList<>();
        ds_KichThuoc = dao_KichThuoc.getAllKichThuoc();

        cmb_KichThuoc.removeAllItems();
        cmb_KichThuoc.addItem("");
        for (KichThuoc kichThuoc : ds_KichThuoc) {
            cmb_KichThuoc.addItem(kichThuoc.getKichThuoc());
        }

        //Doc du lieu ComboBox mau sac
        ArrayList<MauSac> ds_MauSac = new ArrayList<>();
        ds_MauSac = dao_MauSac.getAllMauSac();

        cmb_MauSac.removeAllItems();
        cmb_MauSac.addItem("");
        for (MauSac mauSac : ds_MauSac) {
            cmb_MauSac.addItem(mauSac.getMauSac());
        }

        //Doc du lieu ComboBox phan loai
        ArrayList<PhanLoai> ds_PhanLoai = new ArrayList<>();
        ds_PhanLoai = dao_PhanLoai.getAllPhanLoaiCuaPhuKien();

        cmb_PhanLoai.removeAllItems();
        cmb_PhanLoai.addItem("");
        for (PhanLoai phanLoai : ds_PhanLoai) {
            cmb_PhanLoai.addItem(phanLoai.getLoaiSanPham());
        }

        //Doc du lieu ComboBox nha cung cap
        ArrayList<NhaCungCap> ds_NhaCungCap = new ArrayList<>();
        ds_NhaCungCap = dao_NhaCungCap.getAllNhaCungCap();

        cmb_NCC.removeAllItems();
        cmb_NCC.addItem("");
        for (NhaCungCap nhaCungCap : ds_NhaCungCap) {
            cmb_NCC.addItem(nhaCungCap.getTenNCC());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_XoaTrang;
    private javax.swing.JComboBox<String> cmb_ChatLieu;
    private javax.swing.JComboBox<String> cmb_KichThuoc;
    private javax.swing.JComboBox<String> cmb_MauSac;
    private javax.swing.JComboBox<String> cmb_NCC;
    private javax.swing.JComboBox<String> cmb_PhanLoai;
    private com.toedter.calendar.JDateChooser dch_NgayNhap;
    private javax.swing.JLabel lbl_ChatLieu;
    private javax.swing.JLabel lbl_GiaBan;
    private javax.swing.JLabel lbl_GiaNhap;
    private javax.swing.JLabel lbl_HinhAnhSP;
    private javax.swing.JLabel lbl_KichThuoc;
    private javax.swing.JLabel lbl_MaPK;
    private javax.swing.JLabel lbl_MauSac;
    private javax.swing.JLabel lbl_NCC;
    private javax.swing.JLabel lbl_NgayNhap;
    private javax.swing.JLabel lbl_PhanLoai;
    private javax.swing.JLabel lbl_SoLuong;
    private javax.swing.JLabel lbl_TenPK;
    private javax.swing.JLabel lbl_TieuDe;
    private javax.swing.JPanel pnl_DanhSachPhuKien;
    private javax.swing.JPanel pnl_HinhAnhSanPham;
    private javax.swing.JPanel pnl_NutChucNang;
    private javax.swing.JPanel pnl_PK_TieuDe;
    private javax.swing.JPanel pnl_ThongTin;
    private javax.swing.JScrollPane scr_DanhSachPhuKien;
    private javax.swing.JTable tbl_PhuKien;
    private javax.swing.JTextField txt_GiaBan;
    private javax.swing.JTextField txt_GiaNhap;
    private javax.swing.JTextField txt_MaPK;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_TenPK;
    // End of variables declaration//GEN-END:variables
}
