/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fit.iuh.qlbhtt;

import java.awt.Color;
import javax.swing.UIManager;

import javax.swing.table.DefaultTableModel;

import fit.iuh.dao.INhanVienDao;
import fit.iuh.dao.ITaiKhoanDao;
import fit.iuh.entity.*;
import fit.iuh.util.RMIClientUtil;

import java.rmi.RemoteException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DMX
 */
public   class ManHinh_TaiKhoan_QuanLy extends javax.swing.JPanel {

    private ITaiKhoanDao daoTaiKhoan;
    private INhanVienDao daoNhanVien;
    private DefaultTableModel modelTaiKhoan;

    /**
     * Creates new form quanly
     */
    public   ManHinh_TaiKhoan_QuanLy() throws SQLException, RemoteException {
        daoTaiKhoan = RMIClientUtil.getTaiKhoanDao();
        daoNhanVien = RMIClientUtil.getNhanVienDao();

        initComponents();

        tbl_TaiKhoan.setDefaultEditor(Object.class, null); //Không cho chỉnh sửa cột
        tbl_TaiKhoan.getTableHeader().setReorderingAllowed(false); //Không cho di chuyển cột
        modelTaiKhoan = (DefaultTableModel) tbl_TaiKhoan.getModel();
        loadDuLieuChucVu();
        docDuLieuLenBang();
    }

    /**
     * Load dữ liệu comboBox chức vụ
     */
    public synchronized  void loadDuLieuChucVu() throws RemoteException {
        String giaTriKiemTa = null;
        for (TaiKhoan tk : daoTaiKhoan.getAllTaiKhoan()) {
            if (giaTriKiemTa != null && giaTriKiemTa.equals(tk.getPhanQuyen())) {
                continue;
            }
            giaTriKiemTa = tk.getPhanQuyen();
            cmb_ChucVu.addItem(tk.getPhanQuyen());
        }

    }

    /**
     * Mã hóa dữ liệu mật khẩu khi load lên bảng
     *
     * @param plainPassword
     * @return
     */
    private synchronized String maHoaMatKhau(String plainPassword) {
        //Thay thế những ký tự bằng *
        StringBuilder maHoa = new StringBuilder();
        for (int i = 0; i < plainPassword.length(); i++) {
            maHoa.append("*");
        }
        return maHoa.toString();
    }

    /**
     * Đọc dữ liệu và load dữ liệu lên table
     */
    public synchronized  void docDuLieuLenBang() throws RemoteException {
        modelTaiKhoan = (DefaultTableModel) tbl_TaiKhoan.getModel();
        for (TaiKhoan taiKhoan : daoTaiKhoan.getAllTaiKhoanConHoatDong()) {

            NhanVien nhanVien = daoNhanVien.getNhanVienTheoMa(taiKhoan.getNhanVien().getMaNV());

            Object[] o = new Object[4];
            o[0] = taiKhoan.getTenTaiKhoan();
            o[1] = maHoaMatKhau(taiKhoan.getMatKhau());
            o[2] = nhanVien.getHoTen();
            o[3] = taiKhoan.getPhanQuyen();
            modelTaiKhoan.addRow(o);
        }
    }

    /**
     * Xử lý đổi mật khẩu
     */
    public synchronized  void xuLyDoiMatKhau() throws RemoteException {
        String tenTaiKhoan = txt_TenTK.getText();
        String matKhau = txt_MatKhau.getText();
        NhanVien nhanVien = daoNhanVien.getNhanVienTheoTen(txt_TenNV.getText());
        String phanQuyen = cmb_ChucVu.getSelectedItem().toString();

        int row = tbl_TaiKhoan.getSelectedRow();
        if (row != -1) {
            TaiKhoan tk = new TaiKhoan(tenTaiKhoan, matKhau, phanQuyen, nhanVien, true);
            daoTaiKhoan.doiMatKhauTaiKhoan(tk);
            for (int i = 0; i < tbl_TaiKhoan.getRowCount(); i++) {
                if (tenTaiKhoan.equalsIgnoreCase(tbl_TaiKhoan.getValueAt(row, 0).toString())) {
                    tbl_TaiKhoan.setValueAt(maHoaMatKhau(matKhau), row, 1);
                }
            }
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu không thành công!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private synchronized void initComponents() {

        pnl_DanhSachTaiKhoan = new javax.swing.JPanel();
        scr_DanhSachTaiKhoan = new javax.swing.JScrollPane();
        tbl_TaiKhoan = new javax.swing.JTable();
        pnl_QA_TieuDe = new javax.swing.JPanel();
        lbl_TieuDe1 = new javax.swing.JLabel();
        pnl_ThongTin = new javax.swing.JPanel();
        txt_MatKhau = new javax.swing.JTextField();
        txt_TenTK = new javax.swing.JTextField();
        lbl_TenTK = new javax.swing.JLabel();
        lbl_MatKhau = new javax.swing.JLabel();
        lbl_TenNV = new javax.swing.JLabel();
        lbl_ChucVu = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JTextField();
        cmb_ChucVu = new javax.swing.JComboBox<>();
        pnl_NutChucNang = new javax.swing.JPanel();
        btn_DoiMatKhau = new javax.swing.JButton();
        btn_XacNhan = new javax.swing.JButton();

        setBackground(new java.awt.Color(199, 210, 213));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));

        scr_DanhSachTaiKhoan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách tài khoản", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tbl_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_TaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên tài khoản", "Mật khẩu", "Tên nhân viên", "Chức vụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public synchronized  Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_TaiKhoan.setRowHeight(35);
        tbl_TaiKhoan.setShowGrid(true);
        tbl_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized  void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    tbl_TaiKhoanMouseClicked(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        scr_DanhSachTaiKhoan.setViewportView(tbl_TaiKhoan);

        lbl_TieuDe1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        lbl_TieuDe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TieuDe1.setText("QUẢN LÝ TÀI KHOẢN");
        lbl_TieuDe1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        lbl_TieuDe1.setPreferredSize(new java.awt.Dimension(181, 40));

        javax.swing.GroupLayout pnl_QA_TieuDeLayout = new javax.swing.GroupLayout(pnl_QA_TieuDe);
        pnl_QA_TieuDe.setLayout(pnl_QA_TieuDeLayout);
        pnl_QA_TieuDeLayout.setHorizontalGroup(
            pnl_QA_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_QA_TieuDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TieuDe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_QA_TieuDeLayout.setVerticalGroup(
            pnl_QA_TieuDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_TieuDe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_DanhSachTaiKhoanLayout = new javax.swing.GroupLayout(pnl_DanhSachTaiKhoan);
        pnl_DanhSachTaiKhoan.setLayout(pnl_DanhSachTaiKhoanLayout);
        pnl_DanhSachTaiKhoanLayout.setHorizontalGroup(
            pnl_DanhSachTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scr_DanhSachTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
            .addComponent(pnl_QA_TieuDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_DanhSachTaiKhoanLayout.setVerticalGroup(
            pnl_DanhSachTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DanhSachTaiKhoanLayout.createSequentialGroup()
                .addComponent(pnl_QA_TieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scr_DanhSachTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        );

        pnl_ThongTin.setBackground(new java.awt.Color(199, 210, 213));
        pnl_ThongTin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txt_MatKhau.setEditable(false);
        txt_MatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MatKhau.addActionListener(new java.awt.event.ActionListener() {
            public synchronized  void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatKhauActionPerformed(evt);
            }
        });

        txt_TenTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TenTK.addActionListener(new java.awt.event.ActionListener() {
            public synchronized  void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenTKActionPerformed(evt);
            }
        });

        lbl_TenTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_TenTK.setText("Tên tài khoản");

        lbl_MatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_MatKhau.setText("Mật khẩu");

        lbl_TenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_TenNV.setText("Tên nhân viên");

        lbl_ChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_ChucVu.setText("Chức vụ");

        txt_TenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TenNV.addActionListener(new java.awt.event.ActionListener() {
            public synchronized  void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenNVActionPerformed(evt);
            }
        });

        cmb_ChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_ChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả" }));
        cmb_ChucVu.addItemListener(new java.awt.event.ItemListener() {
            public synchronized  void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_ChucVuItemStateChanged(evt);
            }
        });
        cmb_ChucVu.addActionListener(new java.awt.event.ActionListener() {
            public synchronized  void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ThongTinLayout = new javax.swing.GroupLayout(pnl_ThongTin);
        pnl_ThongTin.setLayout(pnl_ThongTinLayout);
        pnl_ThongTinLayout.setHorizontalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ThongTinLayout.setVerticalGroup(
            pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThongTinLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_ThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pnl_NutChucNang.setBackground(new java.awt.Color(199, 210, 213));

        btn_DoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_DoiMatKhau.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-password-30.png")); // NOI18N
        btn_DoiMatKhau.setText("Đổi mật khẩu");
        btn_DoiMatKhau.setBorder(null);
        btn_DoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized  void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_DoiMatKhauMouseEntered(evt);
            }
            public synchronized  void mouseExited(java.awt.event.MouseEvent evt) {
                btn_DoiMatKhauMouseExited(evt);
            }
        });
        btn_DoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public synchronized  void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn_DoiMatKhauActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        btn_XacNhan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btn_XacNhan.setIcon(new javax.swing.ImageIcon("src/main/java/fit/iuh/imageGD/icons8-save-30.png")); // NOI18N
        btn_XacNhan.setText("Xác nhận");
        btn_XacNhan.setBorder(null);
        btn_XacNhan.setEnabled(false);
        btn_XacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public synchronized  void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_XacNhanMouseEntered(evt);
            }
            public synchronized  void mouseExited(java.awt.event.MouseEvent evt) {
                btn_XacNhanMouseExited(evt);
            }
        });
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public synchronized  void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btn_XacNhanActionPerformed(evt);
                } catch (RemoteException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout pnl_NutChucNangLayout = new javax.swing.GroupLayout(pnl_NutChucNang);
        pnl_NutChucNang.setLayout(pnl_NutChucNangLayout);
        pnl_NutChucNangLayout.setHorizontalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addGroup(pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_DoiMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnl_NutChucNangLayout.setVerticalGroup(
            pnl_NutChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_NutChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btn_DoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(pnl_DanhSachTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_DanhSachTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_ThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnl_NutChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private synchronized void txt_MatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatKhauActionPerformed

    private synchronized void txt_TenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenTKActionPerformed

    private synchronized void txt_TenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenNVActionPerformed

    private synchronized void btn_DoiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoiMatKhauMouseEntered
        btn_DoiMatKhau.setBackground(new Color(0x9EDDFF));
        btn_DoiMatKhau.setForeground(new Color(0x141E46));
    }//GEN-LAST:event_btn_DoiMatKhauMouseEntered

    private synchronized void btn_DoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoiMatKhauMouseExited
        btn_DoiMatKhau.setBackground(UIManager.getColor("Menu.background"));
        btn_DoiMatKhau.setForeground(UIManager.getColor("Menu.foreground"));
    }//GEN-LAST:event_btn_DoiMatKhauMouseExited

    private synchronized void cmb_ChucVuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_ChucVuItemStateChanged

    }//GEN-LAST:event_cmb_ChucVuItemStateChanged

    private synchronized void cmb_ChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ChucVuActionPerformed

    private synchronized void tbl_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) throws RemoteException {//GEN-FIRST:event_tbl_TaiKhoanMouseClicked
        int row = tbl_TaiKhoan.getSelectedRow();
        if (row != -1) {
            txt_TenTK.setText(tbl_TaiKhoan.getValueAt(row, 0).toString());
            if (btn_DoiMatKhau.getText().equals("Hủy")) {
                txt_MatKhau.setText(daoTaiKhoan.getMatKhau(tbl_TaiKhoan.getValueAt(row, 0).toString()));
            } else {
                txt_MatKhau.setText(tbl_TaiKhoan.getValueAt(row, 1).toString());
            }
            txt_TenNV.setText(tbl_TaiKhoan.getValueAt(row, 2).toString());
            cmb_ChucVu.setSelectedItem(tbl_TaiKhoan.getValueAt(row, 3).toString());
        }

    }//GEN-LAST:event_tbl_TaiKhoanMouseClicked

    private synchronized void btn_DoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_btn_DoiMatKhauActionPerformed
        int row = tbl_TaiKhoan.getSelectedRow();
        if (row != -1) {
            String tenTK = tbl_TaiKhoan.getValueAt(row, 0).toString();
            String giaiMa = daoTaiKhoan.getMatKhau(tenTK);
            if (btn_DoiMatKhau.getText().equals("Đổi mật khẩu")) {
                btn_DoiMatKhau.setText("Hủy");
                btn_XacNhan.setEnabled(true);

                txt_MatKhau.setText(giaiMa);
                txt_MatKhau.setEditable(true);
            } else if (btn_DoiMatKhau.getText().equals("Hủy")) {
                btn_DoiMatKhau.setText("Đổi mật khẩu");
                btn_XacNhan.setEnabled(false);
                txt_MatKhau.setText(maHoaMatKhau(giaiMa));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần đổi mật khẩu!");
        }


    }//GEN-LAST:event_btn_DoiMatKhauActionPerformed

    private synchronized void btn_XacNhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XacNhanMouseEntered
        if (btn_XacNhan.isEnabled()) {
            btn_XacNhan.setBackground(new Color(0x9EDDFF));
            btn_XacNhan.setForeground(new Color(0x141E46));
        }
    }//GEN-LAST:event_btn_XacNhanMouseEntered

    private synchronized void btn_XacNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XacNhanMouseExited
        if (btn_XacNhan.isEnabled()) {
            btn_XacNhan.setBackground(UIManager.getColor("Menu.background"));
            btn_XacNhan.setForeground(UIManager.getColor("Menu.foreground"));
        }
    }//GEN-LAST:event_btn_XacNhanMouseExited

    private synchronized void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) throws RemoteException {//GEN-FIRST:event_btn_XacNhanActionPerformed
        xuLyDoiMatKhau();
        int row = tbl_TaiKhoan.getSelectedRow();
        String tenTK = tbl_TaiKhoan.getValueAt(row, 0).toString();
        String giaiMa = daoTaiKhoan.getMatKhau(tenTK);
        if (btn_DoiMatKhau.getText().equalsIgnoreCase("Hủy")) {
            btn_DoiMatKhau.setText("Đổi mật khẩu");
            txt_MatKhau.setText(maHoaMatKhau(giaiMa));
            btn_XacNhan.setBackground(UIManager.getColor("Menu.background"));
            btn_XacNhan.setForeground(UIManager.getColor("Menu.foreground"));
            btn_XacNhan.setEnabled(false);
        }
    }//GEN-LAST:event_btn_XacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DoiMatKhau;
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JComboBox<String> cmb_ChucVu;
    private javax.swing.JLabel lbl_ChucVu;
    private javax.swing.JLabel lbl_MatKhau;
    private javax.swing.JLabel lbl_TenNV;
    private javax.swing.JLabel lbl_TenTK;
    private javax.swing.JLabel lbl_TieuDe1;
    private javax.swing.JPanel pnl_DanhSachTaiKhoan;
    private javax.swing.JPanel pnl_NutChucNang;
    private javax.swing.JPanel pnl_QA_TieuDe;
    private javax.swing.JPanel pnl_ThongTin;
    private javax.swing.JScrollPane scr_DanhSachTaiKhoan;
    private javax.swing.JTable tbl_TaiKhoan;
    private javax.swing.JTextField txt_MatKhau;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_TenTK;
    // End of variables declaration//GEN-END:variables
}
